/*
 * This file is part of the ThreatModeling SDK.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package us.springett.threatmodeling.model;

/**
 * An enum of all classified CAPECs.
 * This class generated from https://capec.mitre.org/data/xml/capec_v2.8.xml
 *
 * @since 1.0.0
 */
public enum CAPEC {

    CAPEC_1(1, "Accessing Functionality Not Properly Constrained by ACLs"),
    CAPEC_2(2, "Inducing Account Lockout"),
    CAPEC_3(3, "Using Leading 'Ghost' Character Sequences to Bypass Input Filters"),
    CAPEC_4(4, "Using Alternative IP Address Encodings"),
    CAPEC_5(5, "Blue Boxing"),
    CAPEC_6(6, "Argument Injection"),
    CAPEC_7(7, "Blind SQL Injection"),
    CAPEC_8(8, "Buffer Overflow in an API Call"),
    CAPEC_9(9, "Buffer Overflow in Local Command-Line Utilities"),
    CAPEC_10(10, "Buffer Overflow via Environment Variables"),
    CAPEC_11(11, "Cause Web Server Misclassification"),
    CAPEC_12(12, "Choosing Message Identifier"),
    CAPEC_13(13, "Subverting Environment Variable Values"),
    CAPEC_14(14, "Client-side Injection-induced Buffer Overflow"),
    CAPEC_15(15, "Command Delimiters"),
    CAPEC_16(16, "Dictionary-based Password Attack"),
    CAPEC_17(17, "Accessing, Modifying or Executing Executable Files"),
    CAPEC_18(18, "Embedding Scripts in Non-Script Elements"),
    CAPEC_19(19, "Embedding Scripts within Scripts"),
    CAPEC_20(20, "Encryption Brute Forcing"),
    CAPEC_21(21, "Exploitation of Trusted Credentials"),
    CAPEC_22(22, "Exploiting Trust in Client"),
    CAPEC_23(23, "File Content Injection"),
    CAPEC_24(24, "Filter Failure through Buffer Overflow"),
    CAPEC_25(25, "Forced Deadlock"),
    CAPEC_26(26, "Leveraging Race Conditions"),
    CAPEC_27(27, "Leveraging Race Conditions via Symbolic Links"),
    CAPEC_28(28, "Fuzzing"),
    CAPEC_29(29, "Leveraging Time-of-Check and Time-of-Use (TOCTOU) Race Conditions"),
    CAPEC_30(30, "Hijacking a Privileged Thread of Execution"),
    CAPEC_31(31, "Accessing/Intercepting/Modifying HTTP Cookies"),
    CAPEC_32(32, "Embedding Scripts in HTTP Query Strings"),
    CAPEC_33(33, "HTTP Request Smuggling"),
    CAPEC_34(34, "HTTP Response Splitting"),
    CAPEC_35(35, "Leverage Executable Code in Non-Executable Files"),
    CAPEC_36(36, "Using Unpublished APIs"),
    CAPEC_37(37, "Retrieve Embedded Sensitive Data"),
    CAPEC_38(38, "Leveraging/Manipulating Configuration File Search Paths"),
    CAPEC_39(39, "Manipulating Opaque Client-based Data Tokens"),
    CAPEC_40(40, "Manipulating Writeable Terminal Devices"),
    CAPEC_41(41, "Using Meta-characters in E-mail Headers to Inject Malicious Payloads"),
    CAPEC_42(42, "MIME Conversion"),
    CAPEC_43(43, "Exploiting Multiple Input Interpretation Layers"),
    CAPEC_44(44, "Overflow Binary Resource File"),
    CAPEC_45(45, "Buffer Overflow via Symbolic Links"),
    CAPEC_46(46, "Overflow Variables and Tags"),
    CAPEC_47(47, "Buffer Overflow via Parameter Expansion"),
    CAPEC_48(48, "Passing Local Filenames to Functions That Expect a URL"),
    CAPEC_49(49, "Password Brute Forcing"),
    CAPEC_50(50, "Password Recovery Exploitation"),
    CAPEC_51(51, "Poison Web Service Registry"),
    CAPEC_52(52, "Embedding NULL Bytes"),
    CAPEC_53(53, "Postfix, Null Terminate, and Backslash"),
    CAPEC_54(54, "Query System for Information"),
    CAPEC_55(55, "Rainbow Table Password Cracking"),
    CAPEC_56(56, "Removing/short-circuiting 'guard logic'"),
    CAPEC_57(57, "Utilizing REST's Trust in the System Resource to Register Man in the Middle"),
    CAPEC_58(58, "Restful Privilege Elevation"),
    CAPEC_59(59, "Session Credential Falsification through Prediction"),
    CAPEC_60(60, "Reusing Session IDs (aka Session Replay)"),
    CAPEC_61(61, "Session Fixation"),
    CAPEC_62(62, "Cross Site Request Forgery (aka Session Riding)"),
    CAPEC_63(63, "Simple Script Injection"),
    CAPEC_64(64, "Using Slashes and URL Encoding Combined to Bypass Validation Logic"),
    CAPEC_65(65, "Sniff Application Code"),
    CAPEC_66(66, "SQL Injection"),
    CAPEC_67(67, "String Format Overflow in syslog()"),
    CAPEC_68(68, "Subvert Code-signing Facilities"),
    CAPEC_69(69, "Target Programs with Elevated Privileges"),
    CAPEC_70(70, "Try Common(default) Usernames and Passwords"),
    CAPEC_71(71, "Using Unicode Encoding to Bypass Validation Logic"),
    CAPEC_72(72, "URL Encoding"),
    CAPEC_73(73, "User-Controlled Filename"),
    CAPEC_74(74, "Manipulating User State"),
    CAPEC_75(75, "Manipulating Writeable Configuration Files"),
    CAPEC_76(76, "Manipulating Input to File System Calls"),
    CAPEC_77(77, "Manipulating User-Controlled Variables"),
    CAPEC_78(78, "Using Escaped Slashes in Alternate Encoding"),
    CAPEC_79(79, "Using Slashes in Alternate Encoding"),
    CAPEC_80(80, "Using UTF-8 Encoding to Bypass Validation Logic"),
    CAPEC_81(81, "Web Logs Tampering"),
    CAPEC_82(82, "Violating Implicit Assumptions Regarding XML Content (aka XML Denial of Service (XDoS))"),
    CAPEC_83(83, "XPath Injection"),
    CAPEC_84(84, "XQuery Injection"),
    CAPEC_85(85, "AJAX Fingerprinting"),
    CAPEC_86(86, "Embedding Script (XSS) in HTTP Headers"),
    CAPEC_87(87, "Forceful Browsing"),
    CAPEC_88(88, "OS Command Injection"),
    CAPEC_89(89, "Pharming"),
    CAPEC_90(90, "Reflection Attack in Authentication Protocol"),
    CAPEC_91(91, "XSS in IMG Tags"),
    CAPEC_92(92, "Forced Integer Overflow"),
    CAPEC_93(93, "Log Injection-Tampering-Forging"),
    CAPEC_94(94, "Man in the Middle Attack"),
    CAPEC_95(95, "WSDL Scanning"),
    CAPEC_96(96, "Block Access to Libraries"),
    CAPEC_97(97, "Cryptanalysis"),
    CAPEC_98(98, "Phishing"),
    CAPEC_99(99, "XML Parser Attack"),
    CAPEC_100(100, "Overflow Buffers"),
    CAPEC_101(101, "Server Side Include (SSI) Injection"),
    CAPEC_102(102, "Session Sidejacking"),
    CAPEC_103(103, "Clickjacking"),
    CAPEC_104(104, "Cross Zone Scripting"),
    CAPEC_105(105, "HTTP Request Splitting"),
    CAPEC_106(106, "Cross Site Scripting through Log Files"),
    CAPEC_107(107, "Cross Site Tracing"),
    CAPEC_108(108, "Command Line Execution through SQL Injection"),
    CAPEC_109(109, "Object Relational Mapping Injection"),
    CAPEC_110(110, "SQL Injection through SOAP Parameter Tampering"),
    CAPEC_111(111, "JSON Hijacking (aka JavaScript Hijacking)"),
    CAPEC_112(112, "Brute Force"),
    CAPEC_113(113, "API Manipulation"),
    CAPEC_114(114, "Authentication Abuse"),
    CAPEC_115(115, "Authentication Bypass"),
    CAPEC_116(116, "Excavation"),
    CAPEC_117(117, "Interception"),
    CAPEC_120(120, "Double Encoding"),
    CAPEC_121(121, "Exploit Test APIs"),
    CAPEC_122(122, "Privilege Abuse"),
    CAPEC_123(123, "Buffer Manipulation"),
    CAPEC_124(124, "Attack through Shared Data"),
    CAPEC_125(125, "Flooding"),
    CAPEC_126(126, "Path Traversal"),
    CAPEC_127(127, "Directory Indexing"),
    CAPEC_128(128, "Integer Attacks"),
    CAPEC_129(129, "Pointer Attack"),
    CAPEC_130(130, "Excessive Allocation"),
    CAPEC_131(131, "Resource Leak Exposure"),
    CAPEC_132(132, "Symlink Attack"),
    CAPEC_133(133, "Try All Common Switches"),
    CAPEC_134(134, "Email Injection"),
    CAPEC_135(135, "Format String Injection"),
    CAPEC_136(136, "LDAP Injection"),
    CAPEC_137(137, "Parameter Injection"),
    CAPEC_138(138, "Reflection Injection"),
    CAPEC_139(139, "Relative Path Traversal"),
    CAPEC_140(140, "Bypassing of Intermediate Forms in Multiple-Form Sets"),
    CAPEC_141(141, "Cache Poisoning"),
    CAPEC_142(142, "DNS Cache Poisoning"),
    CAPEC_143(143, "Detect Unpublicized Web Pages"),
    CAPEC_144(144, "Detect Unpublicized Web Services"),
    CAPEC_145(145, "Checksum Spoofing"),
    CAPEC_146(146, "XML Schema Poisoning"),
    CAPEC_147(147, "XML Ping of the Death"),
    CAPEC_148(148, "Content Spoofing"),
    CAPEC_149(149, "Explore for Predictable Temporary File Names"),
    CAPEC_150(150, "Collect Data from Common Resource Locations"),
    CAPEC_151(151, "Identity Spoofing"),
    CAPEC_153(153, "Input Data Manipulation"),
    CAPEC_154(154, "Resource Location Spoofing"),
    CAPEC_155(155, "Screen Temporary Files for Sensitive Information"),
    CAPEC_157(157, "Sniffing Attacks"),
    CAPEC_158(158, "Sniffing Network Traffic"),
    CAPEC_159(159, "Redirect Access to Libraries"),
    CAPEC_160(160, "Exploit Script-Based APIs"),
    CAPEC_161(161, "Infrastructure Manipulation"),
    CAPEC_162(162, "Manipulating Hidden Fields"),
    CAPEC_163(163, "Spear Phishing"),
    CAPEC_164(164, "Mobile Phishing (aka MobPhishing)"),
    CAPEC_165(165, "File Manipulation"),
    CAPEC_166(166, "Force the System to Reset Values"),
    CAPEC_167(167, "White Box Reverse Engineering"),
    CAPEC_168(168, "Windows ::DATA Alternate Data Stream"),
    CAPEC_169(169, "Footprinting"),
    CAPEC_170(170, "Web Application Fingerprinting"),
    CAPEC_171(171, "Variable Manipulation"),
    CAPEC_173(173, "Action Spoofing"),
    CAPEC_174(174, "Flash Parameter Injection"),
    CAPEC_175(175, "Code Inclusion"),
    CAPEC_176(176, "Configuration/Environment Manipulation"),
    CAPEC_177(177, "Create files with the same name as files protected with a higher classification"),
    CAPEC_178(178, "Cross-Site Flashing"),
    CAPEC_179(179, "Calling Micro-Services Directly"),
    CAPEC_180(180, "Exploiting Incorrectly Configured Access Control Security Levels"),
    CAPEC_181(181, "Flash File Overlay"),
    CAPEC_182(182, "Flash Injection"),
    CAPEC_183(183, "IMAP/SMTP Command Injection"),
    CAPEC_184(184, "Software Integrity Attack"),
    CAPEC_185(185, "Malicious Software Download"),
    CAPEC_186(186, "Malicious Software Update"),
    CAPEC_187(187, "Malicious Automated Software Update"),
    CAPEC_188(188, "Reverse Engineering"),
    CAPEC_189(189, "Black Box Reverse Engineering"),
    CAPEC_190(190, "Reverse Engineer an Executable to Expose Assumed Hidden Functionality or Content"),
    CAPEC_191(191, "Read Sensitive Strings Within an Executable"),
    CAPEC_192(192, "Protocol Analysis"),
    CAPEC_193(193, "PHP Remote File Inclusion"),
    CAPEC_194(194, "Fake the Source of Data"),
    CAPEC_195(195, "Principal Spoof"),
    CAPEC_196(196, "Session Credential Falsification through Forging"),
    CAPEC_197(197, "XML Entity Expansion"),
    CAPEC_198(198, "Cross-Site Scripting in Error Pages"),
    CAPEC_199(199, "Cross-Site Scripting Using Alternate Syntax"),
    CAPEC_200(200, "Removal of filters: Input filters, output filters, data masking"),
    CAPEC_201(201, "XML Entity Blowup"),
    CAPEC_202(202, "Create Malicious Client"),
    CAPEC_203(203, "Manipulate Application Registry Values"),
    CAPEC_204(204, "Lifting Sensitive Data Embedded in Cache"),
    CAPEC_205(205, "Lifting credential(s)/key material embedded in client distributions (thick or thin)"),
    CAPEC_206(206, "Lifting signing key and signing malicious code from a production environment"),
    CAPEC_207(207, "Removing Important Client Functionality"),
    CAPEC_208(208, "Removing/short-circuiting 'Purse' logic: removing/mutating 'cash' decrements"),
    CAPEC_209(209, "Cross-Site Scripting Using MIME Type Mismatch"),
    CAPEC_211(211, "Leveraging web tools (e.g. Mozilla's GreaseMonkey, Firebug) to change application behavior"),
    CAPEC_212(212, "Functionality Misuse"),
    CAPEC_213(213, "Directory Traversal"),
    CAPEC_214(214, "Fuzzing for garnering J2EE/.NET-based stack traces, for application mapping"),
    CAPEC_215(215, "Fuzzing and observing application log data/errors for application mapping"),
    CAPEC_216(216, "Communication Channel Manipulation"),
    CAPEC_217(217, "Exploiting Incorrectly Configured SSL"),
    CAPEC_218(218, "Spoofing of UDDI/ebXML Messages"),
    CAPEC_219(219, "XML Routing Detour Attacks"),
    CAPEC_220(220, "Client-Server Protocol Manipulation"),
    CAPEC_221(221, "XML External Entities"),
    CAPEC_222(222, "iFrame Overlay"),
    CAPEC_224(224, "Fingerprinting"),
    CAPEC_226(226, "Session Credential Falsification through Manipulation"),
    CAPEC_227(227, "Sustained Client Engagement"),
    CAPEC_228(228, "DTD Injection"),
    CAPEC_229(229, "XML Attribute Blowup"),
    CAPEC_230(230, "XML Nested Payloads"),
    CAPEC_231(231, "XML Oversized Payloads"),
    CAPEC_233(233, "Privilege Escalation"),
    CAPEC_234(234, "Hijacking a privileged process"),
    CAPEC_235(235, "Implementing a callback to system routine (old AWT Queue)"),
    CAPEC_236(236, "Catching exception throw/signal from privileged block"),
    CAPEC_237(237, "Calling Signed Code From Another Language Within A Sandbox Allow This "),
    CAPEC_238(238, "Using URL/codebase / G.A.C. (code source) to convince sandbox of privilege"),
    CAPEC_239(239, "Subversion of authorization checks: cache filtering, programmatic security, etc."),
    CAPEC_240(240, "Resource Injection"),
    CAPEC_241(241, "Code Injection"),
    CAPEC_242(242, "Code Injection"),
    CAPEC_243(243, "Cross-Site Scripting in Attributes"),
    CAPEC_244(244, "Cross-Site Scripting via Encoded URI Schemes "),
    CAPEC_245(245, "Cross-Site Scripting Using Doubled Characters, e.g. %3C%3Cscript"),
    CAPEC_246(246, "Cross-Site Scripting Using Flash"),
    CAPEC_247(247, "Cross-Site Scripting with Masking through Invalid Characters in Identifiers"),
    CAPEC_248(248, "Command Injection"),
    CAPEC_249(249, "Linux Terminal Injection"),
    CAPEC_250(250, "XML Injection"),
    CAPEC_251(251, "Local Code Inclusion"),
    CAPEC_252(252, "PHP Local File Inclusion"),
    CAPEC_253(253, "Remote Code Inclusion"),
    CAPEC_254(254, "DTD Injection in a SOAP Message"),
    CAPEC_256(256, "SOAP Array Overflow"),
    CAPEC_257(257, "Abuse of Transaction Data Structure"),
    CAPEC_258(258, "Passively Sniffing and Capturing Application Code Bound for an Authorized Client During Dynamic Update"),
    CAPEC_259(259, "Passively Sniffing and Capturing Application Code Bound for an Authorized Client During Patching"),
    CAPEC_260(260, "Passively Sniffing and Capturing Application Code Bound for an Authorized Client During Initial Distribution"),
    CAPEC_261(261, "Fuzzing for garnering other adjacent user/sensitive data"),
    CAPEC_263(263, "Force Use of Corrupted Files"),
    CAPEC_264(264, "Environment Variable Manipulation"),
    CAPEC_265(265, "Global variable manipulation"),
    CAPEC_266(266, "Manipulate Canonicalization"),
    CAPEC_267(267, "Leverage Alternate Encoding"),
    CAPEC_268(268, "Audit Log Manipulation"),
    CAPEC_269(269, "DEPRECATED: Registry Manipulation"),
    CAPEC_270(270, "Modification of Registry Run Keys"),
    CAPEC_271(271, "Schema Poisoning"),
    CAPEC_272(272, "Protocol Manipulation"),
    CAPEC_273(273, "HTTP Response Smuggling"),
    CAPEC_274(274, "HTTP Verb Tampering"),
    CAPEC_275(275, "DNS Rebinding"),
    CAPEC_276(276, "Inter-component Protocol Manipulation"),
    CAPEC_277(277, "Data Interchange Protocol Manipulation"),
    CAPEC_278(278, "Web Services Protocol Manipulation"),
    CAPEC_279(279, "Soap Manipulation"),
    CAPEC_280(280, "SOAP Parameter Tampering"),
    CAPEC_285(285, "ICMP Echo Request Ping"),
    CAPEC_287(287, "TCP SYN Scan"),
    CAPEC_288(288, "DEPRECATED: ICMP Echo Request Ping"),
    CAPEC_289(289, "DEPRECATED: Infrastructure-based footprinting"),
    CAPEC_290(290, "Enumerate Mail Exchange (MX) Records"),
    CAPEC_291(291, "DNS Zone Transfers"),
    CAPEC_292(292, "Host Discovery"),
    CAPEC_293(293, "Traceroute Route Enumeration"),
    CAPEC_294(294, "ICMP Address Mask Request"),
    CAPEC_295(295, "ICMP Timestamp Request"),
    CAPEC_296(296, "ICMP Information Request"),
    CAPEC_297(297, "TCP ACK Ping"),
    CAPEC_298(298, "UDP Ping"),
    CAPEC_299(299, "TCP SYN Ping"),
    CAPEC_300(300, "Port Scanning"),
    CAPEC_301(301, "TCP Connect Scan"),
    CAPEC_302(302, "TCP FIN scan"),
    CAPEC_303(303, "TCP Xmas Scan"),
    CAPEC_304(304, "TCP Null Scan"),
    CAPEC_305(305, "TCP ACK Scan"),
    CAPEC_306(306, "TCP Window Scan"),
    CAPEC_307(307, "TCP RPC Scan"),
    CAPEC_308(308, "UDP Scan"),
    CAPEC_309(309, "Network Topology Mapping"),
    CAPEC_310(310, "Scanning for Vulnerable Software"),
    CAPEC_311(311, "OS Fingerprinting"),
    CAPEC_312(312, "Active OS Fingerprinting"),
    CAPEC_313(313, "Passive OS Fingerprinting"),
    CAPEC_314(314, "IP Fingerprinting Probes"),
    CAPEC_315(315, "TCP/IP Fingerprinting Probes"),
    CAPEC_316(316, "ICMP Fingerprinting Probes"),
    CAPEC_317(317, "IP ID Sequencing Probe"),
    CAPEC_318(318, "IP 'ID' Echoed Byte-Order Probe"),
    CAPEC_319(319, "IP (DF) 'Don't Fragment Bit' Echoing Probe"),
    CAPEC_320(320, "TCP Timestamp Probe"),
    CAPEC_321(321, "TCP Sequence Number Probe"),
    CAPEC_322(322, "TCP (ISN) Greatest Common Divisor Probe"),
    CAPEC_323(323, "TCP (ISN) Counter Rate Probe"),
    CAPEC_324(324, "TCP (ISN) Sequence Predictability Probe"),
    CAPEC_325(325, "TCP Congestion Control Flag (ECN) Probe"),
    CAPEC_326(326, "TCP Initial Window Size Probe"),
    CAPEC_327(327, "TCP Options Probe"),
    CAPEC_328(328, "TCP 'RST' Flag Checksum Probe"),
    CAPEC_329(329, "ICMP Error Message Quoting Probe"),
    CAPEC_330(330, "ICMP Error Message Echoing Integrity Probe"),
    CAPEC_331(331, "ICMP IP Total Length Field Probe"),
    CAPEC_332(332, "ICMP IP 'ID' Field Error Message Probe"),
    CAPEC_383(383, "Harvesting Usernames or UserIDs via Application API Event Monitoring"),
    CAPEC_384(384, "Application API Message Manipulation via Man-in-the-Middle"),
    CAPEC_385(385, "Transaction or Event Tampering via Application API Manipulation"),
    CAPEC_386(386, "Application API Navigation Remapping"),
    CAPEC_387(387, "Navigation Remapping To Propagate Malicious Content"),
    CAPEC_388(388, "Application API Button Hijacking"),
    CAPEC_389(389, "Content Spoofing Via Application API Manipulation"),
    CAPEC_390(390, "Bypassing Physical Security"),
    CAPEC_391(391, "Bypassing Physical Locks"),
    CAPEC_392(392, "Lock Bumping"),
    CAPEC_393(393, "Lock Picking"),
    CAPEC_394(394, "Using a Snap Gun Lock to Force a Lock"),
    CAPEC_395(395, "Bypassing Electronic Locks and Access Controls"),
    CAPEC_396(396, "Bypassing Card or Badge-Based Systems"),
    CAPEC_397(397, "Cloning Magnetic Strip Cards"),
    CAPEC_398(398, "Magnetic Strip Card Brute Force Attacks"),
    CAPEC_399(399, "Cloning RFID Cards or Chips"),
    CAPEC_400(400, "RFID Chip Deactivation or Destruction"),
    CAPEC_401(401, "Hacking Hardware"),
    CAPEC_402(402, "Bypassing ATA Password Security"),
    CAPEC_404(404, "Social Information Gathering Attacks"),
    CAPEC_405(405, "Social Information Gathering via Research"),
    CAPEC_406(406, "Social Information Gathering via Dumpster Diving"),
    CAPEC_407(407, "Social Information Gathering via Pretexting"),
    CAPEC_408(408, "Information Gathering from Traditional Sources"),
    CAPEC_409(409, "Information Gathering from Non-Traditional Sources"),
    CAPEC_410(410, "Information Elicitation via Social Engineering"),
    CAPEC_411(411, "DEPRECATED: Pretexting"),
    CAPEC_412(412, "Pretexting via Customer Service"),
    CAPEC_413(413, "Pretexting via Tech Support"),
    CAPEC_414(414, "Pretexting via Delivery Person"),
    CAPEC_415(415, "Pretexting via Phone"),
    CAPEC_416(416, "Target Influence via Social Engineering"),
    CAPEC_417(417, "Target Influence via Perception of Reciprocation"),
    CAPEC_418(418, "Target Influence via Perception of Obligation"),
    CAPEC_419(419, "Target Influence via Perception of Concession"),
    CAPEC_420(420, "Target Influence via Perception of Scarcity"),
    CAPEC_421(421, "Target Influence via Perception of Authority"),
    CAPEC_422(422, "Target Influence via Perception of Commitment and Consistency"),
    CAPEC_423(423, "Target Influence via Perception of Liking"),
    CAPEC_424(424, "Target Influence via Perception of Consensus or Social Proof"),
    CAPEC_425(425, "Target Influence via Framing"),
    CAPEC_426(426, "Target Influence via Manipulation of Incentives"),
    CAPEC_427(427, "Target Influence via Psychological Principles"),
    CAPEC_428(428, "Target Influence via Modes of Thinking"),
    CAPEC_429(429, "Target Influence via Eye Cues"),
    CAPEC_430(430, "Target Influence via Micro-Expressions"),
    CAPEC_431(431, "Target Influence via Neuro-Linguistic Programming (NLP)"),
    CAPEC_432(432, "Target Influence via Voice in NLP"),
    CAPEC_433(433, "Target Influence via The Human Buffer Overflow"),
    CAPEC_434(434, "Target Influence via Interview and Interrogation"),
    CAPEC_435(435, "Target Influence via Instant Rapport"),
    CAPEC_438(438, "Modification During Manufacture"),
    CAPEC_439(439, "Manipulation During Distribution"),
    CAPEC_440(440, "Hardware Integrity Attack"),
    CAPEC_441(441, "Malicious Logic Insertion"),
    CAPEC_442(442, "Malicious Logic Inserted Into To Product Software"),
    CAPEC_443(443, "Malicious Logic Inserted Into Product Software by Authorized Developer"),
    CAPEC_444(444, "Development Alteration"),
    CAPEC_445(445, "Malicious Logic Insertion into Product Software via Configuration Management Manipulation"),
    CAPEC_446(446, "Malicious Logic Insertion into Product Software via Inclusion of 3rd Party Component Dependency"),
    CAPEC_447(447, "Design Alteration"),
    CAPEC_448(448, "Malware Infection into Product Software"),
    CAPEC_449(449, "Malware Propagation via USB Stick"),
    CAPEC_450(450, "Malware Propagation via USB U3 Autorun"),
    CAPEC_451(451, "Malware Propagation via Infected Peripheral Device"),
    CAPEC_452(452, "Malicious Logic Insertion into Product Hardware"),
    CAPEC_453(453, "Malicious Logic Insertion via Counterfeit Hardware"),
    CAPEC_454(454, "Modification of Existing Components with Counterfeit Hardware"),
    CAPEC_455(455, "Malicious Logic Insertion via Inclusion of Counterfeit Hardware Components"),
    CAPEC_456(456, "Malicious Logic Insertion into Product Memory"),
    CAPEC_457(457, "USB Memory Attacks"),
    CAPEC_458(458, "Flash Memory Attacks"),
    CAPEC_459(459, "Creating a Rogue Certificate Authority Certificate"),
    CAPEC_460(460, "HTTP Parameter Pollution (HPP)"),
    CAPEC_461(461, "Web Services API Signature Forgery Leveraging Hash Function Extension Weakness"),
    CAPEC_462(462, "Cross-Domain Search Timing"),
    CAPEC_463(463, "Padding Oracle Crypto Attack"),
    CAPEC_464(464, "Evercookie"),
    CAPEC_465(465, "Transparent Proxy Abuse"),
    CAPEC_466(466, "Leveraging Active Man in the Middle Attacks to Bypass Same Origin Policy"),
    CAPEC_467(467, "Cross Site Identification"),
    CAPEC_468(468, "Generic Cross-Browser Cross-Domain Theft"),
    CAPEC_469(469, "HTTP DoS"),
    CAPEC_470(470, "Expanding Control over the Operating System from the Database"),
    CAPEC_471(471, "DLL Search Order Hijacking"),
    CAPEC_472(472, "Browser Fingerprinting"),
    CAPEC_473(473, "Signature Spoof"),
    CAPEC_474(474, "Signature Spoofing by Key Theft"),
    CAPEC_475(475, "Signature Spoofing by Improper Validation"),
    CAPEC_476(476, "Signature Spoofing by Misrepresentation"),
    CAPEC_477(477, "Signature Spoofing by Mixing Signed and Unsigned Content"),
    CAPEC_482(482, "TCP Flood"),
    CAPEC_484(484, "XML Client-Side Attack"),
    CAPEC_485(485, "Signature Spoofing by Key Recreation"),
    CAPEC_486(486, "UDP Flood"),
    CAPEC_487(487, "ICMP Flood"),
    CAPEC_488(488, "HTTP Flood"),
    CAPEC_489(489, "SSL Flood"),
    CAPEC_490(490, "Amplification"),
    CAPEC_491(491, "XML Quadratic Expansion"),
    CAPEC_492(492, "Regular Expression Exponential Blowup"),
    CAPEC_493(493, "SOAP Array Blowup"),
    CAPEC_494(494, "TCP Fragmentation"),
    CAPEC_495(495, "UDP Fragmentation"),
    CAPEC_496(496, "ICMP Fragmentation"),
    CAPEC_498(498, "Probe iOS Screenshots"),
    CAPEC_499(499, "Intent Intercept"),
    CAPEC_500(500, "WebView Injection"),
    CAPEC_501(501, "Activity Hijack"),
    CAPEC_502(502, "Intent Spoof"),
    CAPEC_503(503, "WebView Exposure"),
    CAPEC_504(504, "Task Impersonation"),
    CAPEC_505(505, "Scheme Squatting"),
    CAPEC_506(506, "Tapjacking"),
    CAPEC_507(507, "Physical Theft"),
    CAPEC_510(510, "SaaS User Request Forgery"),
    CAPEC_511(511, "Infiltration of Software Development Environment"),
    CAPEC_516(516, "Hardware Component Substitution During Baselining"),
    CAPEC_517(517, "Documentation Alteration to Circumvent Dial-down"),
    CAPEC_518(518, "Documentation Alteration to Produce Under-performing Systems"),
    CAPEC_519(519, "Documentation Alteration to Cause Errors in System Design"),
    CAPEC_520(520, "Counterfeit Hardware Component Inserted During Product Assembly"),
    CAPEC_521(521, "Hardware Design Specifications Are Altered"),
    CAPEC_522(522, "Malicious Hardware Component Replacement"),
    CAPEC_523(523, "Malicious Software Implanted"),
    CAPEC_524(524, "Rogue Integration Procedures"),
    CAPEC_528(528, "XML Flood"),
    CAPEC_529(529, "Malware-Directed Internal Reconnaissance"),
    CAPEC_530(530, "Provide Counterfeit Component"),
    CAPEC_531(531, "Hardware Component Substitution"),
    CAPEC_532(532, "Altered Installed BIOS"),
    CAPEC_533(533, "Malicious Manual Software Update"),
    CAPEC_534(534, "Malicious Hardware Update"),
    CAPEC_535(535, "Malicious Gray Market Hardware"),
    CAPEC_536(536, "Data Injected During Configuration"),
    CAPEC_537(537, "Infiltration of Hardware Development Environment"),
    CAPEC_538(538, "Open Source Libraries Altered"),
    CAPEC_539(539, "ASIC With Malicious Functionality"),
    CAPEC_540(540, "Overread Buffers"),
    CAPEC_541(541, "Application Fingerprinting"),
    CAPEC_542(542, "Targeted Malware"),
    CAPEC_543(543, "Counterfeit Websites"),
    CAPEC_544(544, "Counterfeit Organizations"),
    CAPEC_545(545, "Pull Data from System Resources"),
    CAPEC_546(546, "Probe Application Memory"),
    CAPEC_547(547, "Physical Destruction of Device or Component"),
    CAPEC_548(548, "Contaminate Resource"),
    CAPEC_549(549, "Local Execution of Code"),
    CAPEC_550(550, "Install New Service"),
    CAPEC_551(551, "Modify Existing Service"),
    CAPEC_552(552, "Install Rootkit "),
    CAPEC_554(554, "Functionality Bypass"),
    CAPEC_555(555, "Remote Services with Stolen Credentials"),
    CAPEC_556(556, "Replace File Extension Handlers"),
    CAPEC_557(557, "Schedule Software To Run"),
    CAPEC_558(558, "Replace Trusted Executable"),
    CAPEC_560(560, "Use of Known Domain Credentials"),
    CAPEC_561(561, "Windows Admin Shares with Stolen Credentials"),
    CAPEC_562(562, "Modify Shared File"),
    CAPEC_563(563, "Add Malicious File to Shared Webroot"),
    CAPEC_564(564, "Run Software at Logon"),
    CAPEC_566(566, "Dump Password Hashes"),
    CAPEC_567(567, "Obtain Data via Utilities"),
    CAPEC_568(568, "Capture Credentials via Keylogger"),
    CAPEC_569(569, "Collect Data as Provided by Users"),
    CAPEC_570(570, "Signature-Based Avoidance"),
    CAPEC_571(571, "Block Logging to Central Repository"),
    CAPEC_572(572, "Artificially Inflate File Sizes"),
    CAPEC_573(573, "Process Footprinting"),
    CAPEC_574(574, "Services Footprinting"),
    CAPEC_575(575, "Account Footprinting"),
    CAPEC_576(576, "Group Permission Footprinting"),
    CAPEC_577(577, "Owner Footprinting"),
    CAPEC_578(578, "Disable Security Software"),
    CAPEC_579(579, "Replace Winlogon Helper DLL"),
    CAPEC_580(580, "Application Footprinting"),
    CAPEC_581(581, "Security Software Footprinting"),
    CAPEC_601(601, "Jamming"),
    CAPEC_602(602, "Degradation"),
    CAPEC_603(603, "Blockage"),
    CAPEC_604(604, "Wi-Fi Jamming"),
    CAPEC_605(605, "Cellular Jamming"),
    CAPEC_606(606, "Weakening of Cellular Encryption"),
    CAPEC_607(607, "Obstruction"),
    CAPEC_608(608, "Cryptanalysis of Cellular Encryption"),
    CAPEC_609(609, "Cellular Traffic Intercept"),
    CAPEC_610(610, "Cellular Data Injection"),
    CAPEC_611(611, "BitSquatting"),
    CAPEC_612(612, "WiFi MAC Address Tracking"),
    CAPEC_613(613, "WiFi SSID Tracking"),
    CAPEC_614(614, "Rooting SIM CardS"),
    CAPEC_615(615, "Evil Twin Wi-Fi Attack"),
    CAPEC_616(616, "Patiently Waiting at Incorrect Location"),
    CAPEC_617(617, "Cellular Rogue Base Station"),
    CAPEC_618(618, "Cellular Broadcast Message Request"),
    CAPEC_619(619, "Signal Strength Tracking"),
    CAPEC_620(620, "Drop Encryption Level"),
    CAPEC_621(621, "Analysis of Packet Timing and Sizes"),
    CAPEC_622(622, "Electromagnetic Side-Channel Attack"),
    CAPEC_623(623, "Compromising Emanations Attack"),
    CAPEC_624(624, "Fault Injection"),
    CAPEC_625(625, "Mobile Device Fault Injection"),
    CAPEC_626(626, "Smudge Attack"),
    CAPEC_627(627, "Counterfeit GPS Signals"),
    CAPEC_628(628, "Carry-Off GPS Attack"),
    CAPEC_629(629, "Unauthorized Use of Device Resources");

    private int id;
    private String name;

    CAPEC(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

}
