/*
 * This file is part of the ThreatModeling SDK.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package us.springett.threatmodeling.model;

/**
 * An enum of all classified CWEs.
 * This class generated from https://cwe.mitre.org/data/xml/cwec_v2.9.xml
 *
 * @since 1.0.0
 */
public enum CWE {

    CWE_1(1, "Location"),
    CWE_2(2, "Environment"),
    CWE_3(3, "Technology-specific Environment Issues"),
    CWE_4(4, "J2EE Environment Issues"),
    CWE_5(5, "J2EE Misconfiguration: Data Transmission Without Encryption"),
    CWE_6(6, "J2EE Misconfiguration: Insufficient Session-ID Length"),
    CWE_7(7, "J2EE Misconfiguration: Missing Custom Error Page"),
    CWE_8(8, "J2EE Misconfiguration: Entity Bean Declared Remote"),
    CWE_9(9, "J2EE Misconfiguration: Weak Access Permissions for EJB Methods"),
    CWE_10(10, "ASP.NET Environment Issues"),
    CWE_11(11, "ASP.NET Misconfiguration: Creating Debug Binary"),
    CWE_12(12, "ASP.NET Misconfiguration: Missing Custom Error Page"),
    CWE_13(13, "ASP.NET Misconfiguration: Password in Configuration File"),
    CWE_14(14, "Compiler Removal of Code to Clear Buffers"),
    CWE_15(15, "External Control of System or Configuration Setting"),
    CWE_16(16, "Configuration"),
    CWE_17(17, "Code"),
    CWE_18(18, "Source Code"),
    CWE_19(19, "Data Handling"),
    CWE_20(20, "Improper Input Validation"),
    CWE_21(21, "Pathname Traversal and Equivalence Errors"),
    CWE_22(22, "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"),
    CWE_23(23, "Relative Path Traversal"),
    CWE_24(24, "Path Traversal: '../filedir'"),
    CWE_25(25, "Path Traversal: '/../filedir'"),
    CWE_26(26, "Path Traversal: '/dir/../filename'"),
    CWE_27(27, "Path Traversal: 'dir/../../filename'"),
    CWE_28(28, "Path Traversal: '..\\filedir'"),
    CWE_29(29, "Path Traversal: '\\..\\filename'"),
    CWE_30(30, "Path Traversal: '\\dir\\..\\filename'"),
    CWE_31(31, "Path Traversal: 'dir\\..\\..\\filename'"),
    CWE_32(32, "Path Traversal: '...' (Triple Dot)"),
    CWE_33(33, "Path Traversal: '....' (Multiple Dot)"),
    CWE_34(34, "Path Traversal: '....//'"),
    CWE_35(35, "Path Traversal: '.../...//'"),
    CWE_36(36, "Absolute Path Traversal"),
    CWE_37(37, "Path Traversal: '/absolute/pathname/here'"),
    CWE_38(38, "Path Traversal: '\\absolute\\pathname\\here'"),
    CWE_39(39, "Path Traversal: 'C:dirname'"),
    CWE_40(40, "Path Traversal: '\\UNC\\share\\name\\' (Windows UNC Share)"),
    CWE_41(41, "Improper Resolution of Path Equivalence"),
    CWE_42(42, "Path Equivalence: 'filename.' (Trailing Dot)"),
    CWE_43(43, "Path Equivalence: 'filename....' (Multiple Trailing Dot)"),
    CWE_44(44, "Path Equivalence: 'file.name' (Internal Dot)"),
    CWE_45(45, "Path Equivalence: 'file...name' (Multiple Internal Dot)"),
    CWE_46(46, "Path Equivalence: 'filename ' (Trailing Space)"),
    CWE_47(47, "Path Equivalence: ' filename' (Leading Space)"),
    CWE_48(48, "Path Equivalence: 'file name' (Internal Whitespace)"),
    CWE_49(49, "Path Equivalence: 'filename/' (Trailing Slash)"),
    CWE_50(50, "Path Equivalence: '//multiple/leading/slash'"),
    CWE_51(51, "Path Equivalence: '/multiple//internal/slash'"),
    CWE_52(52, "Path Equivalence: '/multiple/trailing/slash//'"),
    CWE_53(53, "Path Equivalence: '\\multiple\\internal\backslash'"),
    CWE_54(54, "Path Equivalence: 'filedir\\' (Trailing Backslash)"),
    CWE_55(55, "Path Equivalence: '/./' (Single Dot Directory)"),
    CWE_56(56, "Path Equivalence: 'filedir*' (Wildcard)"),
    CWE_57(57, "Path Equivalence: 'fakedir/../realdir/filename'"),
    CWE_58(58, "Path Equivalence: Windows 8.3 Filename"),
    CWE_59(59, "Improper Link Resolution Before File Access ('Link Following')"),
    CWE_60(60, "UNIX Path Link Problems"),
    CWE_61(61, "UNIX Symbolic Link (Symlink) Following"),
    CWE_62(62, "UNIX Hard Link"),
    CWE_63(63, "Windows Path Link Problems"),
    CWE_64(64, "Windows Shortcut Following (.LNK)"),
    CWE_65(65, "Windows Hard Link"),
    CWE_66(66, "Improper Handling of File Names that Identify Virtual Resources"),
    CWE_67(67, "Improper Handling of Windows Device Names"),
    CWE_68(68, "Windows Virtual File Problems"),
    CWE_69(69, "Improper Handling of Windows ::DATA Alternate Data Stream"),
    CWE_70(70, "Mac Virtual File Problems"),
    CWE_71(71, "Apple '.DS_Store'"),
    CWE_72(72, "Improper Handling of Apple HFS+ Alternate Data Stream Path"),
    CWE_73(73, "External Control of File Name or Path"),
    CWE_74(74, "Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')"),
    CWE_75(75, "Failure to Sanitize Special Elements into a Different Plane (Special Element Injection)"),
    CWE_76(76, "Improper Neutralization of Equivalent Special Elements"),
    CWE_77(77, "Improper Neutralization of Special Elements used in a Command ('Command Injection')"),
    CWE_78(78, "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')"),
    CWE_79(79, "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"),
    CWE_80(80, "Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS)"),
    CWE_81(81, "Improper Neutralization of Script in an Error Message Web Page"),
    CWE_82(82, "Improper Neutralization of Script in Attributes of IMG Tags in a Web Page"),
    CWE_83(83, "Improper Neutralization of Script in Attributes in a Web Page"),
    CWE_84(84, "Improper Neutralization of Encoded URI Schemes in a Web Page"),
    CWE_85(85, "Doubled Character XSS Manipulations"),
    CWE_86(86, "Improper Neutralization of Invalid Characters in Identifiers in Web Pages"),
    CWE_87(87, "Improper Neutralization of Alternate XSS Syntax"),
    CWE_88(88, "Argument Injection or Modification"),
    CWE_89(89, "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"),
    CWE_90(90, "Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')"),
    CWE_91(91, "XML Injection (aka Blind XPath Injection)"),
    CWE_92(92, "DEPRECATED: Improper Sanitization of Custom Special Characters"),
    CWE_93(93, "Improper Neutralization of CRLF Sequences ('CRLF Injection')"),
    CWE_94(94, "Improper Control of Generation of Code ('Code Injection')"),
    CWE_95(95, "Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')"),
    CWE_96(96, "Improper Neutralization of Directives in Statically Saved Code ('Static Code Injection')"),
    CWE_97(97, "Improper Neutralization of Server-Side Includes (SSI) Within a Web Page"),
    CWE_98(98, "Improper Control of Filename for Include/Require Statement in PHP Program ('PHP Remote File Inclusion')"),
    CWE_99(99, "Improper Control of Resource Identifiers ('Resource Injection')"),
    CWE_100(100, "Technology-Specific Input Validation Problems"),
    CWE_101(101, "Struts Validation Problems"),
    CWE_102(102, "Struts: Duplicate Validation Forms"),
    CWE_103(103, "Struts: Incomplete validate() Method Definition"),
    CWE_104(104, "Struts: Form Bean Does Not Extend Validation Class"),
    CWE_105(105, "Struts: Form Field Without Validator"),
    CWE_106(106, "Struts: Plug-in Framework not in Use"),
    CWE_107(107, "Struts: Unused Validation Form"),
    CWE_108(108, "Struts: Unvalidated Action Form"),
    CWE_109(109, "Struts: Validator Turned Off"),
    CWE_110(110, "Struts: Validator Without Form Field"),
    CWE_111(111, "Direct Use of Unsafe JNI"),
    CWE_112(112, "Missing XML Validation"),
    CWE_113(113, "Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Response Splitting')"),
    CWE_114(114, "Process Control"),
    CWE_115(115, "Misinterpretation of Input"),
    CWE_116(116, "Improper Encoding or Escaping of Output"),
    CWE_117(117, "Improper Output Neutralization for Logs"),
    CWE_118(118, "Improper Access of Indexable Resource ('Range Error')"),
    CWE_119(119, "Improper Restriction of Operations within the Bounds of a Memory Buffer"),
    CWE_120(120, "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"),
    CWE_121(121, "Stack-based Buffer Overflow"),
    CWE_122(122, "Heap-based Buffer Overflow"),
    CWE_123(123, "Write-what-where Condition"),
    CWE_124(124, "Buffer Underwrite ('Buffer Underflow')"),
    CWE_125(125, "Out-of-bounds Read"),
    CWE_126(126, "Buffer Over-read"),
    CWE_127(127, "Buffer Under-read"),
    CWE_128(128, "Wrap-around Error"),
    CWE_129(129, "Improper Validation of Array Index"),
    CWE_130(130, "Improper Handling of Length Parameter Inconsistency "),
    CWE_131(131, "Incorrect Calculation of Buffer Size"),
    CWE_132(132, "DEPRECATED (Duplicate): Miscalculated Null Termination"),
    CWE_133(133, "String Errors"),
    CWE_134(134, "Use of Externally-Controlled Format String"),
    CWE_135(135, "Incorrect Calculation of Multi-Byte String Length"),
    CWE_136(136, "Type Errors"),
    CWE_137(137, "Representation Errors"),
    CWE_138(138, "Improper Neutralization of Special Elements"),
    CWE_139(139, "DEPRECATED: General Special Element Problems"),
    CWE_140(140, "Improper Neutralization of Delimiters"),
    CWE_141(141, "Improper Neutralization of Parameter/Argument Delimiters"),
    CWE_142(142, "Improper Neutralization of Value Delimiters"),
    CWE_143(143, "Improper Neutralization of Record Delimiters"),
    CWE_144(144, "Improper Neutralization of Line Delimiters"),
    CWE_145(145, "Improper Neutralization of Section Delimiters"),
    CWE_146(146, "Improper Neutralization of Expression/Command Delimiters"),
    CWE_147(147, "Improper Neutralization of Input Terminators"),
    CWE_148(148, "Improper Neutralization of Input Leaders"),
    CWE_149(149, "Improper Neutralization of Quoting Syntax"),
    CWE_150(150, "Improper Neutralization of Escape, Meta, or Control Sequences"),
    CWE_151(151, "Improper Neutralization of Comment Delimiters"),
    CWE_152(152, "Improper Neutralization of Macro Symbols"),
    CWE_153(153, "Improper Neutralization of Substitution Characters"),
    CWE_154(154, "Improper Neutralization of Variable Name Delimiters"),
    CWE_155(155, "Improper Neutralization of Wildcards or Matching Symbols"),
    CWE_156(156, "Improper Neutralization of Whitespace"),
    CWE_157(157, "Failure to Sanitize Paired Delimiters"),
    CWE_158(158, "Improper Neutralization of Null Byte or NUL Character"),
    CWE_159(159, "Failure to Sanitize Special Element"),
    CWE_160(160, "Improper Neutralization of Leading Special Elements"),
    CWE_161(161, "Improper Neutralization of Multiple Leading Special Elements"),
    CWE_162(162, "Improper Neutralization of Trailing Special Elements"),
    CWE_163(163, "Improper Neutralization of Multiple Trailing Special Elements"),
    CWE_164(164, "Improper Neutralization of Internal Special Elements"),
    CWE_165(165, "Improper Neutralization of Multiple Internal Special Elements"),
    CWE_166(166, "Improper Handling of Missing Special Element"),
    CWE_167(167, "Improper Handling of Additional Special Element"),
    CWE_168(168, "Improper Handling of Inconsistent Special Elements"),
    CWE_169(169, "Technology-Specific Special Elements"),
    CWE_170(170, "Improper Null Termination"),
    CWE_171(171, "Cleansing, Canonicalization, and Comparison Errors"),
    CWE_172(172, "Encoding Error"),
    CWE_173(173, "Improper Handling of Alternate Encoding"),
    CWE_174(174, "Double Decoding of the Same Data"),
    CWE_175(175, "Improper Handling of Mixed Encoding"),
    CWE_176(176, "Improper Handling of Unicode Encoding"),
    CWE_177(177, "Improper Handling of URL Encoding (Hex Encoding)"),
    CWE_178(178, "Improper Handling of Case Sensitivity"),
    CWE_179(179, "Incorrect Behavior Order: Early Validation"),
    CWE_180(180, "Incorrect Behavior Order: Validate Before Canonicalize"),
    CWE_181(181, "Incorrect Behavior Order: Validate Before Filter"),
    CWE_182(182, "Collapse of Data into Unsafe Value"),
    CWE_183(183, "Permissive Whitelist"),
    CWE_184(184, "Incomplete Blacklist"),
    CWE_185(185, "Incorrect Regular Expression"),
    CWE_186(186, "Overly Restrictive Regular Expression"),
    CWE_187(187, "Partial Comparison"),
    CWE_188(188, "Reliance on Data/Memory Layout"),
    CWE_189(189, "Numeric Errors"),
    CWE_190(190, "Integer Overflow or Wraparound"),
    CWE_191(191, "Integer Underflow (Wrap or Wraparound)"),
    CWE_192(192, "Integer Coercion Error"),
    CWE_193(193, "Off-by-one Error"),
    CWE_194(194, "Unexpected Sign Extension"),
    CWE_195(195, "Signed to Unsigned Conversion Error"),
    CWE_196(196, "Unsigned to Signed Conversion Error"),
    CWE_197(197, "Numeric Truncation Error"),
    CWE_198(198, "Use of Incorrect Byte Ordering"),
    CWE_199(199, "Information Management Errors"),
    CWE_200(200, "Information Exposure"),
    CWE_201(201, "Information Exposure Through Sent Data"),
    CWE_202(202, "Exposure of Sensitive Data Through Data Queries"),
    CWE_203(203, "Information Exposure Through Discrepancy"),
    CWE_204(204, "Response Discrepancy Information Exposure"),
    CWE_205(205, "Information Exposure Through Behavioral Discrepancy"),
    CWE_206(206, "Information Exposure of Internal State Through Behavioral Inconsistency"),
    CWE_207(207, "Information Exposure Through an External Behavioral Inconsistency"),
    CWE_208(208, "Information Exposure Through Timing Discrepancy"),
    CWE_209(209, "Information Exposure Through an Error Message"),
    CWE_210(210, "Information Exposure Through Self-generated Error Message"),
    CWE_211(211, "Information Exposure Through Externally-generated Error Message"),
    CWE_212(212, "Improper Cross-boundary Removal of Sensitive Data"),
    CWE_213(213, "Intentional Information Exposure"),
    CWE_214(214, "Information Exposure Through Process Environment"),
    CWE_215(215, "Information Exposure Through Debug Information"),
    CWE_216(216, "Containment Errors (Container Errors)"),
    CWE_217(217, "DEPRECATED: Failure to Protect Stored Data from Modification"),
    CWE_218(218, "DEPRECATED (Duplicate): Failure to provide confidentiality for stored data"),
    CWE_219(219, "Sensitive Data Under Web Root"),
    CWE_220(220, "Sensitive Data Under FTP Root"),
    CWE_221(221, "Information Loss or Omission"),
    CWE_222(222, "Truncation of Security-relevant Information"),
    CWE_223(223, "Omission of Security-relevant Information"),
    CWE_224(224, "Obscured Security-relevant Information by Alternate Name"),
    CWE_225(225, "DEPRECATED (Duplicate): General Information Management Problems"),
    CWE_226(226, "Sensitive Information Uncleared Before Release"),
    CWE_227(227, "Improper Fulfillment of API Contract ('API Abuse')"),
    CWE_228(228, "Improper Handling of Syntactically Invalid Structure"),
    CWE_229(229, "Improper Handling of Values"),
    CWE_230(230, "Improper Handling of Missing Values"),
    CWE_231(231, "Improper Handling of Extra Values"),
    CWE_232(232, "Improper Handling of Undefined Values"),
    CWE_233(233, "Improper Handling of Parameters"),
    CWE_234(234, "Failure to Handle Missing Parameter"),
    CWE_235(235, "Improper Handling of Extra Parameters"),
    CWE_236(236, "Improper Handling of Undefined Parameters"),
    CWE_237(237, "Improper Handling of Structural Elements"),
    CWE_238(238, "Improper Handling of Incomplete Structural Elements"),
    CWE_239(239, "Failure to Handle Incomplete Element"),
    CWE_240(240, "Improper Handling of Inconsistent Structural Elements"),
    CWE_241(241, "Improper Handling of Unexpected Data Type"),
    CWE_242(242, "Use of Inherently Dangerous Function"),
    CWE_243(243, "Creation of chroot Jail Without Changing Working Directory"),
    CWE_244(244, "Improper Clearing of Heap Memory Before Release ('Heap Inspection')"),
    CWE_245(245, "J2EE Bad Practices: Direct Management of Connections"),
    CWE_246(246, "J2EE Bad Practices: Direct Use of Sockets"),
    CWE_247(247, "DEPRECATED (Duplicate): Reliance on DNS Lookups in a Security Decision"),
    CWE_248(248, "Uncaught Exception"),
    CWE_249(249, "DEPRECATED: Often Misused: Path Manipulation"),
    CWE_250(250, "Execution with Unnecessary Privileges"),
    CWE_251(251, "Often Misused: String Management"),
    CWE_252(252, "Unchecked Return Value"),
    CWE_253(253, "Incorrect Check of Function Return Value"),
    CWE_254(254, "Security Features"),
    CWE_255(255, "Credentials Management"),
    CWE_256(256, "Plaintext Storage of a Password"),
    CWE_257(257, "Storing Passwords in a Recoverable Format"),
    CWE_258(258, "Empty Password in Configuration File"),
    CWE_259(259, "Use of Hard-coded Password"),
    CWE_260(260, "Password in Configuration File"),
    CWE_261(261, "Weak Cryptography for Passwords"),
    CWE_262(262, "Not Using Password Aging"),
    CWE_263(263, "Password Aging with Long Expiration"),
    CWE_264(264, "Permissions, Privileges, and Access Controls"),
    CWE_265(265, "Privilege / Sandbox Issues"),
    CWE_266(266, "Incorrect Privilege Assignment"),
    CWE_267(267, "Privilege Defined With Unsafe Actions"),
    CWE_268(268, "Privilege Chaining"),
    CWE_269(269, "Improper Privilege Management"),
    CWE_270(270, "Privilege Context Switching Error"),
    CWE_271(271, "Privilege Dropping / Lowering Errors"),
    CWE_272(272, "Least Privilege Violation"),
    CWE_273(273, "Improper Check for Dropped Privileges"),
    CWE_274(274, "Improper Handling of Insufficient Privileges"),
    CWE_275(275, "Permission Issues"),
    CWE_276(276, "Incorrect Default Permissions"),
    CWE_277(277, "Insecure Inherited Permissions"),
    CWE_278(278, "Insecure Preserved Inherited Permissions"),
    CWE_279(279, "Incorrect Execution-Assigned Permissions"),
    CWE_280(280, "Improper Handling of Insufficient Permissions or Privileges "),
    CWE_281(281, "Improper Preservation of Permissions"),
    CWE_282(282, "Improper Ownership Management"),
    CWE_283(283, "Unverified Ownership"),
    CWE_284(284, "Improper Access Control"),
    CWE_285(285, "Improper Authorization"),
    CWE_286(286, "Incorrect User Management"),
    CWE_287(287, "Improper Authentication"),
    CWE_288(288, "Authentication Bypass Using an Alternate Path or Channel"),
    CWE_289(289, "Authentication Bypass by Alternate Name"),
    CWE_290(290, "Authentication Bypass by Spoofing"),
    CWE_291(291, "Reliance on IP Address for Authentication"),
    CWE_292(292, "DEPRECATED (Duplicate): Trusting Self-reported DNS Name"),
    CWE_293(293, "Using Referer Field for Authentication"),
    CWE_294(294, "Authentication Bypass by Capture-replay"),
    CWE_295(295, "Improper Certificate Validation"),
    CWE_296(296, "Improper Following of a Certificate's Chain of Trust"),
    CWE_297(297, "Improper Validation of Certificate with Host Mismatch"),
    CWE_298(298, "Improper Validation of Certificate Expiration"),
    CWE_299(299, "Improper Check for Certificate Revocation"),
    CWE_300(300, "Channel Accessible by Non-Endpoint ('Man-in-the-Middle')"),
    CWE_301(301, "Reflection Attack in an Authentication Protocol"),
    CWE_302(302, "Authentication Bypass by Assumed-Immutable Data"),
    CWE_303(303, "Incorrect Implementation of Authentication Algorithm"),
    CWE_304(304, "Missing Critical Step in Authentication"),
    CWE_305(305, "Authentication Bypass by Primary Weakness"),
    CWE_306(306, "Missing Authentication for Critical Function"),
    CWE_307(307, "Improper Restriction of Excessive Authentication Attempts"),
    CWE_308(308, "Use of Single-factor Authentication"),
    CWE_309(309, "Use of Password System for Primary Authentication"),
    CWE_310(310, "Cryptographic Issues"),
    CWE_311(311, "Missing Encryption of Sensitive Data"),
    CWE_312(312, "Cleartext Storage of Sensitive Information"),
    CWE_313(313, "Cleartext Storage in a File or on Disk"),
    CWE_314(314, "Cleartext Storage in the Registry"),
    CWE_315(315, "Cleartext Storage of Sensitive Information in a Cookie"),
    CWE_316(316, "Cleartext Storage of Sensitive Information in Memory"),
    CWE_317(317, "Cleartext Storage of Sensitive Information in GUI"),
    CWE_318(318, "Cleartext Storage of Sensitive Information in Executable"),
    CWE_319(319, "Cleartext Transmission of Sensitive Information"),
    CWE_320(320, "Key Management Errors"),
    CWE_321(321, "Use of Hard-coded Cryptographic Key"),
    CWE_322(322, "Key Exchange without Entity Authentication"),
    CWE_323(323, "Reusing a Nonce, Key Pair in Encryption"),
    CWE_324(324, "Use of a Key Past its Expiration Date"),
    CWE_325(325, "Missing Required Cryptographic Step"),
    CWE_326(326, "Inadequate Encryption Strength"),
    CWE_327(327, "Use of a Broken or Risky Cryptographic Algorithm"),
    CWE_328(328, "Reversible One-Way Hash"),
    CWE_329(329, "Not Using a Random IV with CBC Mode"),
    CWE_330(330, "Use of Insufficiently Random Values"),
    CWE_331(331, "Insufficient Entropy"),
    CWE_332(332, "Insufficient Entropy in PRNG"),
    CWE_333(333, "Improper Handling of Insufficient Entropy in TRNG"),
    CWE_334(334, "Small Space of Random Values"),
    CWE_335(335, "PRNG Seed Error"),
    CWE_336(336, "Same Seed in PRNG"),
    CWE_337(337, "Predictable Seed in PRNG"),
    CWE_338(338, "Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)"),
    CWE_339(339, "Small Seed Space in PRNG"),
    CWE_340(340, "Predictability Problems"),
    CWE_341(341, "Predictable from Observable State"),
    CWE_342(342, "Predictable Exact Value from Previous Values"),
    CWE_343(343, "Predictable Value Range from Previous Values"),
    CWE_344(344, "Use of Invariant Value in Dynamically Changing Context"),
    CWE_345(345, "Insufficient Verification of Data Authenticity"),
    CWE_346(346, "Origin Validation Error"),
    CWE_347(347, "Improper Verification of Cryptographic Signature"),
    CWE_348(348, "Use of Less Trusted Source"),
    CWE_349(349, "Acceptance of Extraneous Untrusted Data With Trusted Data"),
    CWE_350(350, "Reliance on Reverse DNS Resolution for a Security-Critical Action"),
    CWE_351(351, "Insufficient Type Distinction"),
    CWE_352(352, "Cross-Site Request Forgery (CSRF)"),
    CWE_353(353, "Missing Support for Integrity Check"),
    CWE_354(354, "Improper Validation of Integrity Check Value"),
    CWE_355(355, "User Interface Security Issues"),
    CWE_356(356, "Product UI does not Warn User of Unsafe Actions"),
    CWE_357(357, "Insufficient UI Warning of Dangerous Operations"),
    CWE_358(358, "Improperly Implemented Security Check for Standard"),
    CWE_359(359, "Exposure of Private Information ('Privacy Violation')"),
    CWE_360(360, "Trust of System Event Data"),
    CWE_361(361, "Time and State"),
    CWE_362(362, "Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')"),
    CWE_363(363, "Race Condition Enabling Link Following"),
    CWE_364(364, "Signal Handler Race Condition"),
    CWE_365(365, "Race Condition in Switch"),
    CWE_366(366, "Race Condition within a Thread"),
    CWE_367(367, "Time-of-check Time-of-use (TOCTOU) Race Condition"),
    CWE_368(368, "Context Switching Race Condition"),
    CWE_369(369, "Divide By Zero"),
    CWE_370(370, "Missing Check for Certificate Revocation after Initial Check"),
    CWE_371(371, "State Issues"),
    CWE_372(372, "Incomplete Internal State Distinction"),
    CWE_373(373, "DEPRECATED: State Synchronization Error"),
    CWE_374(374, "Passing Mutable Objects to an Untrusted Method"),
    CWE_375(375, "Returning a Mutable Object to an Untrusted Caller"),
    CWE_376(376, "Temporary File Issues"),
    CWE_377(377, "Insecure Temporary File"),
    CWE_378(378, "Creation of Temporary File With Insecure Permissions"),
    CWE_379(379, "Creation of Temporary File in Directory with Incorrect Permissions"),
    CWE_380(380, "Technology-Specific Time and State Issues"),
    CWE_381(381, "J2EE Time and State Issues"),
    CWE_382(382, "J2EE Bad Practices: Use of System.exit()"),
    CWE_383(383, "J2EE Bad Practices: Direct Use of Threads"),
    CWE_384(384, "Session Fixation"),
    CWE_385(385, "Covert Timing Channel"),
    CWE_386(386, "Symbolic Name not Mapping to Correct Object"),
    CWE_387(387, "Signal Errors"),
    CWE_388(388, "Error Handling"),
    CWE_389(389, "Error Conditions, Return Values, Status Codes"),
    CWE_390(390, "Detection of Error Condition Without Action"),
    CWE_391(391, "Unchecked Error Condition"),
    CWE_392(392, "Missing Report of Error Condition"),
    CWE_393(393, "Return of Wrong Status Code"),
    CWE_394(394, "Unexpected Status Code or Return Value"),
    CWE_395(395, "Use of NullPointerException Catch to Detect NULL Pointer Dereference"),
    CWE_396(396, "Declaration of Catch for Generic Exception"),
    CWE_397(397, "Declaration of Throws for Generic Exception"),
    CWE_398(398, "Indicator of Poor Code Quality"),
    CWE_399(399, "Resource Management Errors"),
    CWE_400(400, "Uncontrolled Resource Consumption ('Resource Exhaustion')"),
    CWE_401(401, "Improper Release of Memory Before Removing Last Reference ('Memory Leak')"),
    CWE_402(402, "Transmission of Private Resources into a New Sphere ('Resource Leak')"),
    CWE_403(403, "Exposure of File Descriptor to Unintended Control Sphere ('File Descriptor Leak')"),
    CWE_404(404, "Improper Resource Shutdown or Release"),
    CWE_405(405, "Asymmetric Resource Consumption (Amplification)"),
    CWE_406(406, "Insufficient Control of Network Message Volume (Network Amplification)"),
    CWE_407(407, "Algorithmic Complexity"),
    CWE_408(408, "Incorrect Behavior Order: Early Amplification"),
    CWE_409(409, "Improper Handling of Highly Compressed Data (Data Amplification)"),
    CWE_410(410, "Insufficient Resource Pool"),
    CWE_411(411, "Resource Locking Problems"),
    CWE_412(412, "Unrestricted Externally Accessible Lock"),
    CWE_413(413, "Improper Resource Locking"),
    CWE_414(414, "Missing Lock Check"),
    CWE_415(415, "Double Free"),
    CWE_416(416, "Use After Free"),
    CWE_417(417, "Channel and Path Errors"),
    CWE_418(418, "Channel Errors"),
    CWE_419(419, "Unprotected Primary Channel"),
    CWE_420(420, "Unprotected Alternate Channel"),
    CWE_421(421, "Race Condition During Access to Alternate Channel"),
    CWE_422(422, "Unprotected Windows Messaging Channel ('Shatter')"),
    CWE_423(423, "DEPRECATED (Duplicate): Proxied Trusted Channel"),
    CWE_424(424, "Improper Protection of Alternate Path"),
    CWE_425(425, "Direct Request ('Forced Browsing')"),
    CWE_426(426, "Untrusted Search Path"),
    CWE_427(427, "Uncontrolled Search Path Element"),
    CWE_428(428, "Unquoted Search Path or Element"),
    CWE_429(429, "Handler Errors"),
    CWE_430(430, "Deployment of Wrong Handler"),
    CWE_431(431, "Missing Handler"),
    CWE_432(432, "Dangerous Signal Handler not Disabled During Sensitive Operations"),
    CWE_433(433, "Unparsed Raw Web Content Delivery"),
    CWE_434(434, "Unrestricted Upload of File with Dangerous Type"),
    CWE_435(435, "Interaction Error"),
    CWE_436(436, "Interpretation Conflict"),
    CWE_437(437, "Incomplete Model of Endpoint Features"),
    CWE_438(438, "Behavioral Problems"),
    CWE_439(439, "Behavioral Change in New Version or Environment"),
    CWE_440(440, "Expected Behavior Violation"),
    CWE_441(441, "Unintended Proxy or Intermediary ('Confused Deputy')"),
    CWE_442(442, "Web Problems"),
    CWE_443(443, "DEPRECATED (Duplicate): HTTP response splitting"),
    CWE_444(444, "Inconsistent Interpretation of HTTP Requests ('HTTP Request Smuggling')"),
    CWE_445(445, "User Interface Errors"),
    CWE_446(446, "UI Discrepancy for Security Feature"),
    CWE_447(447, "Unimplemented or Unsupported Feature in UI"),
    CWE_448(448, "Obsolete Feature in UI"),
    CWE_449(449, "The UI Performs the Wrong Action"),
    CWE_450(450, "Multiple Interpretations of UI Input"),
    CWE_451(451, "User Interface (UI) Misrepresentation of Critical Information"),
    CWE_452(452, "Initialization and Cleanup Errors"),
    CWE_453(453, "Insecure Default Variable Initialization"),
    CWE_454(454, "External Initialization of Trusted Variables or Data Stores"),
    CWE_455(455, "Non-exit on Failed Initialization"),
    CWE_456(456, "Missing Initialization of a Variable"),
    CWE_457(457, "Use of Uninitialized Variable"),
    CWE_458(458, "DEPRECATED: Incorrect Initialization"),
    CWE_459(459, "Incomplete Cleanup"),
    CWE_460(460, "Improper Cleanup on Thrown Exception"),
    CWE_461(461, "Data Structure Issues"),
    CWE_462(462, "Duplicate Key in Associative List (Alist)"),
    CWE_463(463, "Deletion of Data Structure Sentinel"),
    CWE_464(464, "Addition of Data Structure Sentinel"),
    CWE_465(465, "Pointer Issues"),
    CWE_466(466, "Return of Pointer Value Outside of Expected Range"),
    CWE_467(467, "Use of sizeof() on a Pointer Type"),
    CWE_468(468, "Incorrect Pointer Scaling"),
    CWE_469(469, "Use of Pointer Subtraction to Determine Size"),
    CWE_470(470, "Use of Externally-Controlled Input to Select Classes or Code ('Unsafe Reflection')"),
    CWE_471(471, "Modification of Assumed-Immutable Data (MAID)"),
    CWE_472(472, "External Control of Assumed-Immutable Web Parameter"),
    CWE_473(473, "PHP External Variable Modification"),
    CWE_474(474, "Use of Function with Inconsistent Implementations"),
    CWE_475(475, "Undefined Behavior for Input to API"),
    CWE_476(476, "NULL Pointer Dereference"),
    CWE_477(477, "Use of Obsolete Functions"),
    CWE_478(478, "Missing Default Case in Switch Statement"),
    CWE_479(479, "Signal Handler Use of a Non-reentrant Function"),
    CWE_480(480, "Use of Incorrect Operator"),
    CWE_481(481, "Assigning instead of Comparing"),
    CWE_482(482, "Comparing instead of Assigning"),
    CWE_483(483, "Incorrect Block Delimitation"),
    CWE_484(484, "Omitted Break Statement in Switch"),
    CWE_485(485, "Insufficient Encapsulation"),
    CWE_486(486, "Comparison of Classes by Name"),
    CWE_487(487, "Reliance on Package-level Scope"),
    CWE_488(488, "Exposure of Data Element to Wrong Session"),
    CWE_489(489, "Leftover Debug Code"),
    CWE_490(490, "Mobile Code Issues"),
    CWE_491(491, "Public cloneable() Method Without Final ('Object Hijack')"),
    CWE_492(492, "Use of Inner Class Containing Sensitive Data"),
    CWE_493(493, "Critical Public Variable Without Final Modifier"),
    CWE_494(494, "Download of Code Without Integrity Check"),
    CWE_495(495, "Private Array-Typed Field Returned From A Public Method"),
    CWE_496(496, "Public Data Assigned to Private Array-Typed Field"),
    CWE_497(497, "Exposure of System Data to an Unauthorized Control Sphere"),
    CWE_498(498, "Cloneable Class Containing Sensitive Information"),
    CWE_499(499, "Serializable Class Containing Sensitive Data"),
    CWE_500(500, "Public Static Field Not Marked Final"),
    CWE_501(501, "Trust Boundary Violation"),
    CWE_502(502, "Deserialization of Untrusted Data"),
    CWE_503(503, "Byte/Object Code"),
    CWE_504(504, "Motivation/Intent"),
    CWE_505(505, "Intentionally Introduced Weakness"),
    CWE_506(506, "Embedded Malicious Code"),
    CWE_507(507, "Trojan Horse"),
    CWE_508(508, "Non-Replicating Malicious Code"),
    CWE_509(509, "Replicating Malicious Code (Virus or Worm)"),
    CWE_510(510, "Trapdoor"),
    CWE_511(511, "Logic/Time Bomb"),
    CWE_512(512, "Spyware"),
    CWE_513(513, "Intentionally Introduced Nonmalicious Weakness"),
    CWE_514(514, "Covert Channel"),
    CWE_515(515, "Covert Storage Channel"),
    CWE_516(516, "DEPRECATED (Duplicate): Covert Timing Channel"),
    CWE_517(517, "Other Intentional, Nonmalicious Weakness"),
    CWE_518(518, "Inadvertently Introduced Weakness"),
    CWE_519(519, ".NET Environment Issues"),
    CWE_520(520, ".NET Misconfiguration: Use of Impersonation"),
    CWE_521(521, "Weak Password Requirements"),
    CWE_522(522, "Insufficiently Protected Credentials"),
    CWE_523(523, "Unprotected Transport of Credentials"),
    CWE_524(524, "Information Exposure Through Caching"),
    CWE_525(525, "Information Exposure Through Browser Caching"),
    CWE_526(526, "Information Exposure Through Environmental Variables"),
    CWE_527(527, "Exposure of CVS Repository to an Unauthorized Control Sphere"),
    CWE_528(528, "Exposure of Core Dump File to an Unauthorized Control Sphere"),
    CWE_529(529, "Exposure of Access Control List Files to an Unauthorized Control Sphere"),
    CWE_530(530, "Exposure of Backup File to an Unauthorized Control Sphere"),
    CWE_531(531, "Information Exposure Through Test Code"),
    CWE_532(532, "Information Exposure Through Log Files"),
    CWE_533(533, "Information Exposure Through Server Log Files"),
    CWE_534(534, "Information Exposure Through Debug Log Files"),
    CWE_535(535, "Information Exposure Through Shell Error Message"),
    CWE_536(536, "Information Exposure Through Servlet Runtime Error Message"),
    CWE_537(537, "Information Exposure Through Java Runtime Error Message"),
    CWE_538(538, "File and Directory Information Exposure"),
    CWE_539(539, "Information Exposure Through Persistent Cookies"),
    CWE_540(540, "Information Exposure Through Source Code"),
    CWE_541(541, "Information Exposure Through Include Source Code"),
    CWE_542(542, "Information Exposure Through Cleanup Log Files"),
    CWE_543(543, "Use of Singleton Pattern Without Synchronization in a Multithreaded Context"),
    CWE_544(544, "Missing Standardized Error Handling Mechanism"),
    CWE_545(545, "Use of Dynamic Class Loading"),
    CWE_546(546, "Suspicious Comment"),
    CWE_547(547, "Use of Hard-coded, Security-relevant Constants"),
    CWE_548(548, "Information Exposure Through Directory Listing"),
    CWE_549(549, "Missing Password Field Masking"),
    CWE_550(550, "Information Exposure Through Server Error Message"),
    CWE_551(551, "Incorrect Behavior Order: Authorization Before Parsing and Canonicalization"),
    CWE_552(552, "Files or Directories Accessible to External Parties"),
    CWE_553(553, "Command Shell in Externally Accessible Directory"),
    CWE_554(554, "ASP.NET Misconfiguration: Not Using Input Validation Framework"),
    CWE_555(555, "J2EE Misconfiguration: Plaintext Password in Configuration File"),
    CWE_556(556, "ASP.NET Misconfiguration: Use of Identity Impersonation"),
    CWE_557(557, "Concurrency Issues"),
    CWE_558(558, "Use of getlogin() in Multithreaded Application"),
    CWE_559(559, "Often Misused: Arguments and Parameters"),
    CWE_560(560, "Use of umask() with chmod-style Argument"),
    CWE_561(561, "Dead Code"),
    CWE_562(562, "Return of Stack Variable Address"),
    CWE_563(563, "Assignment to Variable without Use ('Unused Variable')"),
    CWE_564(564, "SQL Injection: Hibernate"),
    CWE_565(565, "Reliance on Cookies without Validation and Integrity Checking"),
    CWE_566(566, "Authorization Bypass Through User-Controlled SQL Primary Key"),
    CWE_567(567, "Unsynchronized Access to Shared Data in a Multithreaded Context"),
    CWE_568(568, "finalize() Method Without super.finalize()"),
    CWE_569(569, "Expression Issues"),
    CWE_570(570, "Expression is Always False"),
    CWE_571(571, "Expression is Always True"),
    CWE_572(572, "Call to Thread run() instead of start()"),
    CWE_573(573, "Improper Following of Specification by Caller"),
    CWE_574(574, "EJB Bad Practices: Use of Synchronization Primitives"),
    CWE_575(575, "EJB Bad Practices: Use of AWT Swing"),
    CWE_576(576, "EJB Bad Practices: Use of Java I/O"),
    CWE_577(577, "EJB Bad Practices: Use of Sockets"),
    CWE_578(578, "EJB Bad Practices: Use of Class Loader"),
    CWE_579(579, "J2EE Bad Practices: Non-serializable Object Stored in Session"),
    CWE_580(580, "clone() Method Without super.clone()"),
    CWE_581(581, "Object Model Violation: Just One of Equals and Hashcode Defined"),
    CWE_582(582, "Array Declared Public, Final, and Static"),
    CWE_583(583, "finalize() Method Declared Public"),
    CWE_584(584, "Return Inside Finally Block"),
    CWE_585(585, "Empty Synchronized Block"),
    CWE_586(586, "Explicit Call to Finalize()"),
    CWE_587(587, "Assignment of a Fixed Address to a Pointer"),
    CWE_588(588, "Attempt to Access Child of a Non-structure Pointer"),
    CWE_589(589, "Call to Non-ubiquitous API"),
    CWE_590(590, "Free of Memory not on the Heap"),
    CWE_591(591, "Sensitive Data Storage in Improperly Locked Memory"),
    CWE_592(592, "Authentication Bypass Issues"),
    CWE_593(593, "Authentication Bypass: OpenSSL CTX Object Modified after SSL Objects are Created"),
    CWE_594(594, "J2EE Framework: Saving Unserializable Objects to Disk"),
    CWE_595(595, "Comparison of Object References Instead of Object Contents"),
    CWE_596(596, "Incorrect Semantic Object Comparison"),
    CWE_597(597, "Use of Wrong Operator in String Comparison"),
    CWE_598(598, "Information Exposure Through Query Strings in GET Request"),
    CWE_599(599, "Missing Validation of OpenSSL Certificate"),
    CWE_600(600, "Uncaught Exception in Servlet "),
    CWE_601(601, "URL Redirection to Untrusted Site ('Open Redirect')"),
    CWE_602(602, "Client-Side Enforcement of Server-Side Security"),
    CWE_603(603, "Use of Client-Side Authentication"),
    CWE_605(605, "Multiple Binds to the Same Port"),
    CWE_606(606, "Unchecked Input for Loop Condition"),
    CWE_607(607, "Public Static Final Field References Mutable Object"),
    CWE_608(608, "Struts: Non-private Field in ActionForm Class"),
    CWE_609(609, "Double-Checked Locking"),
    CWE_610(610, "Externally Controlled Reference to a Resource in Another Sphere"),
    CWE_611(611, "Improper Restriction of XML External Entity Reference ('XXE')"),
    CWE_612(612, "Information Exposure Through Indexing of Private Data"),
    CWE_613(613, "Insufficient Session Expiration"),
    CWE_614(614, "Sensitive Cookie in HTTPS Session Without 'Secure' Attribute"),
    CWE_615(615, "Information Exposure Through Comments"),
    CWE_616(616, "Incomplete Identification of Uploaded File Variables (PHP)"),
    CWE_617(617, "Reachable Assertion"),
    CWE_618(618, "Exposed Unsafe ActiveX Method"),
    CWE_619(619, "Dangling Database Cursor ('Cursor Injection')"),
    CWE_620(620, "Unverified Password Change"),
    CWE_621(621, "Variable Extraction Error"),
    CWE_622(622, "Improper Validation of Function Hook Arguments"),
    CWE_623(623, "Unsafe ActiveX Control Marked Safe For Scripting"),
    CWE_624(624, "Executable Regular Expression Error"),
    CWE_625(625, "Permissive Regular Expression"),
    CWE_626(626, "Null Byte Interaction Error (Poison Null Byte)"),
    CWE_627(627, "Dynamic Variable Evaluation"),
    CWE_628(628, "Function Call with Incorrectly Specified Arguments"),
    CWE_632(632, "Weaknesses that Affect Files or Directories"),
    CWE_633(633, "Weaknesses that Affect Memory"),
    CWE_634(634, "Weaknesses that Affect System Processes"),
    CWE_636(636, "Not Failing Securely ('Failing Open')"),
    CWE_637(637, "Unnecessary Complexity in Protection Mechanism (Not Using 'Economy of Mechanism')"),
    CWE_638(638, "Not Using Complete Mediation"),
    CWE_639(639, "Authorization Bypass Through User-Controlled Key"),
    CWE_640(640, "Weak Password Recovery Mechanism for Forgotten Password"),
    CWE_641(641, "Improper Restriction of Names for Files and Other Resources"),
    CWE_642(642, "External Control of Critical State Data"),
    CWE_643(643, "Improper Neutralization of Data within XPath Expressions ('XPath Injection')"),
    CWE_644(644, "Improper Neutralization of HTTP Headers for Scripting Syntax"),
    CWE_645(645, "Overly Restrictive Account Lockout Mechanism"),
    CWE_646(646, "Reliance on File Name or Extension of Externally-Supplied File"),
    CWE_647(647, "Use of Non-Canonical URL Paths for Authorization Decisions"),
    CWE_648(648, "Incorrect Use of Privileged APIs"),
    CWE_649(649, "Reliance on Obfuscation or Encryption of Security-Relevant Inputs without Integrity Checking"),
    CWE_650(650, "Trusting HTTP Permission Methods on the Server Side"),
    CWE_651(651, "Information Exposure Through WSDL File"),
    CWE_652(652, "Improper Neutralization of Data within XQuery Expressions ('XQuery Injection')"),
    CWE_653(653, "Insufficient Compartmentalization"),
    CWE_654(654, "Reliance on a Single Factor in a Security Decision"),
    CWE_655(655, "Insufficient Psychological Acceptability"),
    CWE_656(656, "Reliance on Security Through Obscurity"),
    CWE_657(657, "Violation of Secure Design Principles"),
    CWE_662(662, "Improper Synchronization"),
    CWE_663(663, "Use of a Non-reentrant Function in a Concurrent Context"),
    CWE_664(664, "Improper Control of a Resource Through its Lifetime"),
    CWE_665(665, "Improper Initialization"),
    CWE_666(666, "Operation on Resource in Wrong Phase of Lifetime"),
    CWE_667(667, "Improper Locking"),
    CWE_668(668, "Exposure of Resource to Wrong Sphere"),
    CWE_669(669, "Incorrect Resource Transfer Between Spheres"),
    CWE_670(670, "Always-Incorrect Control Flow Implementation"),
    CWE_671(671, "Lack of Administrator Control over Security"),
    CWE_672(672, "Operation on a Resource after Expiration or Release"),
    CWE_673(673, "External Influence of Sphere Definition"),
    CWE_674(674, "Uncontrolled Recursion"),
    CWE_675(675, "Duplicate Operations on Resource"),
    CWE_676(676, "Use of Potentially Dangerous Function"),
    CWE_680(680, "Integer Overflow to Buffer Overflow"),
    CWE_681(681, "Incorrect Conversion between Numeric Types"),
    CWE_682(682, "Incorrect Calculation"),
    CWE_683(683, "Function Call With Incorrect Order of Arguments"),
    CWE_684(684, "Incorrect Provision of Specified Functionality"),
    CWE_685(685, "Function Call With Incorrect Number of Arguments"),
    CWE_686(686, "Function Call With Incorrect Argument Type"),
    CWE_687(687, "Function Call With Incorrectly Specified Argument Value"),
    CWE_688(688, "Function Call With Incorrect Variable or Reference as Argument"),
    CWE_689(689, "Permission Race Condition During Resource Copy"),
    CWE_690(690, "Unchecked Return Value to NULL Pointer Dereference"),
    CWE_691(691, "Insufficient Control Flow Management"),
    CWE_692(692, "Incomplete Blacklist to Cross-Site Scripting"),
    CWE_693(693, "Protection Mechanism Failure"),
    CWE_694(694, "Use of Multiple Resources with Duplicate Identifier"),
    CWE_695(695, "Use of Low-Level Functionality"),
    CWE_696(696, "Incorrect Behavior Order"),
    CWE_697(697, "Insufficient Comparison"),
    CWE_698(698, "Execution After Redirect (EAR)"),
    CWE_703(703, "Improper Check or Handling of Exceptional Conditions"),
    CWE_704(704, "Incorrect Type Conversion or Cast"),
    CWE_705(705, "Incorrect Control Flow Scoping"),
    CWE_706(706, "Use of Incorrectly-Resolved Name or Reference"),
    CWE_707(707, "Improper Enforcement of Message or Data Structure"),
    CWE_708(708, "Incorrect Ownership Assignment"),
    CWE_710(710, "Coding Standards Violation"),
    CWE_712(712, "OWASP Top Ten 2007 Category A1 - Cross Site Scripting (XSS)"),
    CWE_713(713, "OWASP Top Ten 2007 Category A2 - Injection Flaws"),
    CWE_714(714, "OWASP Top Ten 2007 Category A3 - Malicious File Execution"),
    CWE_715(715, "OWASP Top Ten 2007 Category A4 - Insecure Direct Object Reference"),
    CWE_716(716, "OWASP Top Ten 2007 Category A5 - Cross Site Request Forgery (CSRF)"),
    CWE_717(717, "OWASP Top Ten 2007 Category A6 - Information Leakage and Improper Error Handling"),
    CWE_718(718, "OWASP Top Ten 2007 Category A7 - Broken Authentication and Session Management"),
    CWE_719(719, "OWASP Top Ten 2007 Category A8 - Insecure Cryptographic Storage"),
    CWE_720(720, "OWASP Top Ten 2007 Category A9 - Insecure Communications"),
    CWE_721(721, "OWASP Top Ten 2007 Category A10 - Failure to Restrict URL Access"),
    CWE_722(722, "OWASP Top Ten 2004 Category A1 - Unvalidated Input"),
    CWE_723(723, "OWASP Top Ten 2004 Category A2 - Broken Access Control"),
    CWE_724(724, "OWASP Top Ten 2004 Category A3 - Broken Authentication and Session Management"),
    CWE_725(725, "OWASP Top Ten 2004 Category A4 - Cross-Site Scripting (XSS) Flaws"),
    CWE_726(726, "OWASP Top Ten 2004 Category A5 - Buffer Overflows"),
    CWE_727(727, "OWASP Top Ten 2004 Category A6 - Injection Flaws"),
    CWE_728(728, "OWASP Top Ten 2004 Category A7 - Improper Error Handling"),
    CWE_729(729, "OWASP Top Ten 2004 Category A8 - Insecure Storage"),
    CWE_730(730, "OWASP Top Ten 2004 Category A9 - Denial of Service"),
    CWE_731(731, "OWASP Top Ten 2004 Category A10 - Insecure Configuration Management"),
    CWE_732(732, "Incorrect Permission Assignment for Critical Resource"),
    CWE_733(733, "Compiler Optimization Removal or Modification of Security-critical Code"),
    CWE_735(735, "CERT C Secure Coding Section 01 - Preprocessor (PRE)"),
    CWE_736(736, "CERT C Secure Coding Section 02 - Declarations and Initialization (DCL)"),
    CWE_737(737, "CERT C Secure Coding Section 03 - Expressions (EXP)"),
    CWE_738(738, "CERT C Secure Coding Section 04 - Integers (INT)"),
    CWE_739(739, "CERT C Secure Coding Section 05 - Floating Point (FLP)"),
    CWE_740(740, "CERT C Secure Coding Section 06 - Arrays (ARR)"),
    CWE_741(741, "CERT C Secure Coding Section 07 - Characters and Strings (STR)"),
    CWE_742(742, "CERT C Secure Coding Section 08 - Memory Management (MEM)"),
    CWE_743(743, "CERT C Secure Coding Section 09 - Input Output (FIO)"),
    CWE_744(744, "CERT C Secure Coding Section 10 - Environment (ENV)"),
    CWE_745(745, "CERT C Secure Coding Section 11 - Signals (SIG)"),
    CWE_746(746, "CERT C Secure Coding Section 12 - Error Handling (ERR)"),
    CWE_747(747, "CERT C Secure Coding Section 49 - Miscellaneous (MSC)"),
    CWE_748(748, "CERT C Secure Coding Section 50 - POSIX (POS)"),
    CWE_749(749, "Exposed Dangerous Method or Function"),
    CWE_751(751, "2009 Top 25 - Insecure Interaction Between Components"),
    CWE_752(752, "2009 Top 25 - Risky Resource Management"),
    CWE_753(753, "2009 Top 25 - Porous Defenses"),
    CWE_754(754, "Improper Check for Unusual or Exceptional Conditions"),
    CWE_755(755, "Improper Handling of Exceptional Conditions"),
    CWE_756(756, "Missing Custom Error Page"),
    CWE_757(757, "Selection of Less-Secure Algorithm During Negotiation ('Algorithm Downgrade')"),
    CWE_758(758, "Reliance on Undefined, Unspecified, or Implementation-Defined Behavior"),
    CWE_759(759, "Use of a One-Way Hash without a Salt"),
    CWE_760(760, "Use of a One-Way Hash with a Predictable Salt"),
    CWE_761(761, "Free of Pointer not at Start of Buffer"),
    CWE_762(762, "Mismatched Memory Management Routines"),
    CWE_763(763, "Release of Invalid Pointer or Reference"),
    CWE_764(764, "Multiple Locks of a Critical Resource"),
    CWE_765(765, "Multiple Unlocks of a Critical Resource"),
    CWE_766(766, "Critical Variable Declared Public"),
    CWE_767(767, "Access to Critical Private Variable via Public Method"),
    CWE_768(768, "Incorrect Short Circuit Evaluation"),
    CWE_769(769, "File Descriptor Exhaustion"),
    CWE_770(770, "Allocation of Resources Without Limits or Throttling"),
    CWE_771(771, "Missing Reference to Active Allocated Resource"),
    CWE_772(772, "Missing Release of Resource after Effective Lifetime"),
    CWE_773(773, "Missing Reference to Active File Descriptor or Handle"),
    CWE_774(774, "Allocation of File Descriptors or Handles Without Limits or Throttling"),
    CWE_775(775, "Missing Release of File Descriptor or Handle after Effective Lifetime"),
    CWE_776(776, "Improper Restriction of Recursive Entity References in DTDs ('XML Entity Expansion')"),
    CWE_777(777, "Regular Expression without Anchors"),
    CWE_778(778, "Insufficient Logging"),
    CWE_779(779, "Logging of Excessive Data"),
    CWE_780(780, "Use of RSA Algorithm without OAEP"),
    CWE_781(781, "Improper Address Validation in IOCTL with METHOD_NEITHER I/O Control Code"),
    CWE_782(782, "Exposed IOCTL with Insufficient Access Control"),
    CWE_783(783, "Operator Precedence Logic Error"),
    CWE_784(784, "Reliance on Cookies without Validation and Integrity Checking in a Security Decision"),
    CWE_785(785, "Use of Path Manipulation Function without Maximum-sized Buffer"),
    CWE_786(786, "Access of Memory Location Before Start of Buffer"),
    CWE_787(787, "Out-of-bounds Write"),
    CWE_788(788, "Access of Memory Location After End of Buffer"),
    CWE_789(789, "Uncontrolled Memory Allocation"),
    CWE_790(790, "Improper Filtering of Special Elements"),
    CWE_791(791, "Incomplete Filtering of Special Elements"),
    CWE_792(792, "Incomplete Filtering of One or More Instances of Special Elements"),
    CWE_793(793, "Only Filtering One Instance of a Special Element"),
    CWE_794(794, "Incomplete Filtering of Multiple Instances of Special Elements"),
    CWE_795(795, "Only Filtering Special Elements at a Specified Location"),
    CWE_796(796, "Only Filtering Special Elements Relative to a Marker"),
    CWE_797(797, "Only Filtering Special Elements at an Absolute Position"),
    CWE_798(798, "Use of Hard-coded Credentials"),
    CWE_799(799, "Improper Control of Interaction Frequency"),
    CWE_801(801, "2010 Top 25 - Insecure Interaction Between Components"),
    CWE_802(802, "2010 Top 25 - Risky Resource Management"),
    CWE_803(803, "2010 Top 25 - Porous Defenses"),
    CWE_804(804, "Guessable CAPTCHA"),
    CWE_805(805, "Buffer Access with Incorrect Length Value"),
    CWE_806(806, "Buffer Access Using Size of Source Buffer"),
    CWE_807(807, "Reliance on Untrusted Inputs in a Security Decision"),
    CWE_808(808, "2010 Top 25 - Weaknesses On the Cusp"),
    CWE_810(810, "OWASP Top Ten 2010 Category A1 - Injection"),
    CWE_811(811, "OWASP Top Ten 2010 Category A2 - Cross-Site Scripting (XSS)"),
    CWE_812(812, "OWASP Top Ten 2010 Category A3 - Broken Authentication and Session Management"),
    CWE_813(813, "OWASP Top Ten 2010 Category A4 - Insecure Direct Object References"),
    CWE_814(814, "OWASP Top Ten 2010 Category A5 - Cross-Site Request Forgery(CSRF)"),
    CWE_815(815, "OWASP Top Ten 2010 Category A6 - Security Misconfiguration"),
    CWE_816(816, "OWASP Top Ten 2010 Category A7 - Insecure Cryptographic Storage"),
    CWE_817(817, "OWASP Top Ten 2010 Category A8 - Failure to Restrict URL Access"),
    CWE_818(818, "OWASP Top Ten 2010 Category A9 - Insufficient Transport Layer Protection"),
    CWE_819(819, "OWASP Top Ten 2010 Category A10 - Unvalidated Redirects and Forwards"),
    CWE_820(820, "Missing Synchronization"),
    CWE_821(821, "Incorrect Synchronization"),
    CWE_822(822, "Untrusted Pointer Dereference"),
    CWE_823(823, "Use of Out-of-range Pointer Offset"),
    CWE_824(824, "Access of Uninitialized Pointer"),
    CWE_825(825, "Expired Pointer Dereference"),
    CWE_826(826, "Premature Release of Resource During Expected Lifetime"),
    CWE_827(827, "Improper Control of Document Type Definition"),
    CWE_828(828, "Signal Handler with Functionality that is not Asynchronous-Safe"),
    CWE_829(829, "Inclusion of Functionality from Untrusted Control Sphere"),
    CWE_830(830, "Inclusion of Web Functionality from an Untrusted Source"),
    CWE_831(831, "Signal Handler Function Associated with Multiple Signals"),
    CWE_832(832, "Unlock of a Resource that is not Locked"),
    CWE_833(833, "Deadlock"),
    CWE_834(834, "Excessive Iteration"),
    CWE_835(835, "Loop with Unreachable Exit Condition ('Infinite Loop')"),
    CWE_836(836, "Use of Password Hash Instead of Password for Authentication"),
    CWE_837(837, "Improper Enforcement of a Single, Unique Action"),
    CWE_838(838, "Inappropriate Encoding for Output Context"),
    CWE_839(839, "Numeric Range Comparison Without Minimum Check"),
    CWE_840(840, "Business Logic Errors"),
    CWE_841(841, "Improper Enforcement of Behavioral Workflow"),
    CWE_842(842, "Placement of User into Incorrect Group"),
    CWE_843(843, "Access of Resource Using Incompatible Type ('Type Confusion')"),
    CWE_845(845, "CERT Java Secure Coding Section 00 - Input Validation and Data Sanitization (IDS)"),
    CWE_846(846, "CERT Java Secure Coding Section 01 - Declarations and Initialization (DCL)"),
    CWE_847(847, "CERT Java Secure Coding Section 02 - Expressions (EXP)"),
    CWE_848(848, "CERT Java Secure Coding Section 03 - Numeric Types and Operations (NUM)"),
    CWE_849(849, "CERT Java Secure Coding Section 04 - Object Orientation (OBJ)"),
    CWE_850(850, "CERT Java Secure Coding Section 05 - Methods (MET)"),
    CWE_851(851, "CERT Java Secure Coding Section 06 - Exceptional Behavior (ERR)"),
    CWE_852(852, "CERT Java Secure Coding Section 07 - Visibility and Atomicity (VNA)"),
    CWE_853(853, "CERT Java Secure Coding Section 08 - Locking (LCK)"),
    CWE_854(854, "CERT Java Secure Coding Section 09 - Thread APIs (THI)"),
    CWE_855(855, "CERT Java Secure Coding Section 10 - Thread Pools (TPS)"),
    CWE_856(856, "CERT Java Secure Coding Section 11 - Thread-Safety Miscellaneous (TSM)"),
    CWE_857(857, "CERT Java Secure Coding Section 12 - Input Output (FIO)"),
    CWE_858(858, "CERT Java Secure Coding Section 13 - Serialization (SER)"),
    CWE_859(859, "CERT Java Secure Coding Section 14 - Platform Security (SEC)"),
    CWE_860(860, "CERT Java Secure Coding Section 15 - Runtime Environment (ENV)"),
    CWE_861(861, "CERT Java Secure Coding Section 49 - Miscellaneous (MSC)"),
    CWE_862(862, "Missing Authorization"),
    CWE_863(863, "Incorrect Authorization"),
    CWE_864(864, "2011 Top 25 - Insecure Interaction Between Components"),
    CWE_865(865, "2011 Top 25 - Risky Resource Management"),
    CWE_866(866, "2011 Top 25 - Porous Defenses"),
    CWE_867(867, "2011 Top 25 - Weaknesses On the Cusp"),
    CWE_869(869, "CERT C++ Secure Coding Section 01 - Preprocessor (PRE)"),
    CWE_870(870, "CERT C++ Secure Coding Section 02 - Declarations and Initialization (DCL)"),
    CWE_871(871, "CERT C++ Secure Coding Section 03 - Expressions (EXP)"),
    CWE_872(872, "CERT C++ Secure Coding Section 04 - Integers (INT)"),
    CWE_873(873, "CERT C++ Secure Coding Section 05 - Floating Point Arithmetic (FLP)"),
    CWE_874(874, "CERT C++ Secure Coding Section 06 - Arrays and the STL (ARR)"),
    CWE_875(875, "CERT C++ Secure Coding Section 07 - Characters and Strings (STR)"),
    CWE_876(876, "CERT C++ Secure Coding Section 08 - Memory Management (MEM)"),
    CWE_877(877, "CERT C++ Secure Coding Section 09 - Input Output (FIO)"),
    CWE_878(878, "CERT C++ Secure Coding Section 10 - Environment (ENV)"),
    CWE_879(879, "CERT C++ Secure Coding Section 11 - Signals (SIG)"),
    CWE_880(880, "CERT C++ Secure Coding Section 12 - Exceptions and Error Handling (ERR)"),
    CWE_881(881, "CERT C++ Secure Coding Section 13 - Object Oriented Programming (OOP)"),
    CWE_882(882, "CERT C++ Secure Coding Section 14 - Concurrency (CON)"),
    CWE_883(883, "CERT C++ Secure Coding Section 49 - Miscellaneous (MSC)"),
    CWE_885(885, "SFP Primary Cluster: Risky Values"),
    CWE_886(886, "SFP Primary Cluster: Unused entities"),
    CWE_887(887, "SFP Primary Cluster: API"),
    CWE_889(889, "SFP Primary Cluster: Exception Management"),
    CWE_890(890, "SFP Primary Cluster: Memory Access"),
    CWE_891(891, "SFP Primary Cluster: Memory Management"),
    CWE_892(892, "SFP Primary Cluster: Resource Management"),
    CWE_893(893, "SFP Primary Cluster: Path Resolution"),
    CWE_894(894, "SFP Primary Cluster: Synchronization"),
    CWE_895(895, "SFP Primary Cluster: Information Leak"),
    CWE_896(896, "SFP Primary Cluster: Tainted Input"),
    CWE_897(897, "SFP Primary Cluster: Entry Points"),
    CWE_898(898, "SFP Primary Cluster: Authentication"),
    CWE_899(899, "SFP Primary Cluster: Access Control"),
    CWE_901(901, "SFP Primary Cluster: Privilege"),
    CWE_902(902, "SFP Primary Cluster: Channel"),
    CWE_903(903, "SFP Primary Cluster: Cryptography"),
    CWE_904(904, "SFP Primary Cluster: Malware"),
    CWE_905(905, "SFP Primary Cluster: Predictability"),
    CWE_906(906, "SFP Primary Cluster: UI"),
    CWE_907(907, "SFP Primary Cluster: Other"),
    CWE_908(908, "Use of Uninitialized Resource"),
    CWE_909(909, "Missing Initialization of Resource"),
    CWE_910(910, "Use of Expired File Descriptor"),
    CWE_911(911, "Improper Update of Reference Count"),
    CWE_912(912, "Hidden Functionality"),
    CWE_913(913, "Improper Control of Dynamically-Managed Code Resources"),
    CWE_914(914, "Improper Control of Dynamically-Identified Variables"),
    CWE_915(915, "Improperly Controlled Modification of Dynamically-Determined Object Attributes"),
    CWE_916(916, "Use of Password Hash With Insufficient Computational Effort"),
    CWE_917(917, "Improper Neutralization of Special Elements used in an Expression Language Statement ('Expression Language Injection')"),
    CWE_918(918, "Server-Side Request Forgery (SSRF)"),
    CWE_920(920, "Improper Restriction of Power Consumption"),
    CWE_921(921, "Storage of Sensitive Data in a Mechanism without Access Control"),
    CWE_922(922, "Insecure Storage of Sensitive Information"),
    CWE_923(923, "Improper Restriction of Communication Channel to Intended Endpoints"),
    CWE_924(924, "Improper Enforcement of Message Integrity During Transmission in a Communication Channel"),
    CWE_925(925, "Improper Verification of Intent by Broadcast Receiver"),
    CWE_926(926, "Improper Export of Android Application Components"),
    CWE_927(927, "Use of Implicit Intent for Sensitive Communication"),
    CWE_929(929, "OWASP Top Ten 2013 Category A1 - Injection"),
    CWE_930(930, "OWASP Top Ten 2013 Category A2 - Broken Authentication and Session Management"),
    CWE_931(931, "OWASP Top Ten 2013 Category A3 - Cross-Site Scripting (XSS)"),
    CWE_932(932, "OWASP Top Ten 2013 Category A4 - Insecure Direct Object References"),
    CWE_933(933, "OWASP Top Ten 2013 Category A5 - Security Misconfiguration"),
    CWE_934(934, "OWASP Top Ten 2013 Category A6 - Sensitive Data Exposure"),
    CWE_935(935, "OWASP Top Ten 2013 Category A7 - Missing Function Level Access Control"),
    CWE_936(936, "OWASP Top Ten 2013 Category A8 - Cross-Site Request Forgery (CSRF)"),
    CWE_937(937, "OWASP Top Ten 2013 Category A9 - Using Components with Known Vulnerabilities"),
    CWE_938(938, "OWASP Top Ten 2013 Category A10 - Unvalidated Redirects and Forwards"),
    CWE_939(939, "Improper Authorization in Handler for Custom URL Scheme"),
    CWE_940(940, "Improper Verification of Source of a Communication Channel"),
    CWE_941(941, "Incorrectly Specified Destination in a Communication Channel"),
    CWE_942(942, "Overly Permissive Cross-domain Whitelist"),
    CWE_943(943, "Improper Neutralization of Special Elements in Data Query Logic"),
    CWE_944(944, "SFP Secondary Cluster: Access Management"),
    CWE_945(945, "SFP Secondary Cluster: Insecure Resource Access"),
    CWE_946(946, "SFP Secondary Cluster: Insecure Resource Permissions"),
    CWE_947(947, "SFP Secondary Cluster: Authentication Bypass"),
    CWE_948(948, "SFP Secondary Cluster: Digital Certificate"),
    CWE_949(949, "SFP Secondary Cluster: Faulty Endpoint Authentication"),
    CWE_950(950, "SFP Secondary Cluster: Hardcoded Sensitive Data"),
    CWE_951(951, "SFP Secondary Cluster: Insecure Authentication Policy"),
    CWE_952(952, "SFP Secondary Cluster: Missing Authentication"),
    CWE_953(953, "SFP Secondary Cluster: Missing Endpoint Authentication"),
    CWE_954(954, "SFP Secondary Cluster: Multiple Binds to the Same Port"),
    CWE_955(955, "SFP Secondary Cluster: Unrestricted Authentication"),
    CWE_956(956, "SFP Secondary Cluster: Channel Attack"),
    CWE_957(957, "SFP Secondary Cluster: Protocol Error"),
    CWE_958(958, "SFP Secondary Cluster: Broken Cryptography"),
    CWE_959(959, "SFP Secondary Cluster: Weak Cryptography"),
    CWE_960(960, "SFP Secondary Cluster: Ambiguous Exception Type"),
    CWE_961(961, "SFP Secondary Cluster: Incorrect Exception Behavior"),
    CWE_962(962, "SFP Secondary Cluster: Unchecked Status Condition"),
    CWE_963(963, "SFP Secondary Cluster: Exposed Data"),
    CWE_964(964, "SFP Secondary Cluster: Exposure Temporary File"),
    CWE_965(965, "SFP Secondary Cluster: Insecure Session Management"),
    CWE_966(966, "SFP Secondary Cluster: Other Exposures"),
    CWE_967(967, "SFP Secondary Cluster: State Disclosure"),
    CWE_968(968, "SFP Secondary Cluster: Covert Channel"),
    CWE_969(969, "SFP Secondary Cluster: Faulty Memory Release"),
    CWE_970(970, "SFP Secondary Cluster: Faulty Buffer Access"),
    CWE_971(971, "SFP Secondary Cluster: Faulty Pointer Use"),
    CWE_972(972, "SFP Secondary Cluster: Faulty String Expansion"),
    CWE_973(973, "SFP Secondary Cluster: Improper NULL Termination"),
    CWE_974(974, "SFP Secondary Cluster: Incorrect Buffer Length Computation"),
    CWE_975(975, "SFP Secondary Cluster: Architecture"),
    CWE_976(976, "SFP Secondary Cluster: Compiler"),
    CWE_977(977, "SFP Secondary Cluster: Design"),
    CWE_978(978, "SFP Secondary Cluster: Implementation"),
    CWE_979(979, "SFP Secondary Cluster: Failed Chroot Jail"),
    CWE_980(980, "SFP Secondary Cluster: Link in Resource Name Resolution"),
    CWE_981(981, "SFP Secondary Cluster: Path Traversal"),
    CWE_982(982, "SFP Secondary Cluster: Failure to Release Resource"),
    CWE_983(983, "SFP Secondary Cluster: Faulty Resource Use"),
    CWE_984(984, "SFP Secondary Cluster: Life Cycle"),
    CWE_985(985, "SFP Secondary Cluster: Unrestricted Consumption"),
    CWE_986(986, "SFP Secondary Cluster: Missing Lock"),
    CWE_987(987, "SFP Secondary Cluster: Multiple Locks/Unlocks"),
    CWE_988(988, "SFP Secondary Cluster: Race Condition Window"),
    CWE_989(989, "SFP Secondary Cluster: Unrestricted Lock"),
    CWE_990(990, "SFP Secondary Cluster: Tainted Input to Command"),
    CWE_991(991, "SFP Secondary Cluster: Tainted Input to Environment"),
    CWE_992(992, "SFP Secondary Cluster: Faulty Input Transformation"),
    CWE_993(993, "SFP Secondary Cluster: Incorrect Input Handling"),
    CWE_994(994, "SFP Secondary Cluster: Tainted Input to Variable"),
    CWE_995(995, "SFP Secondary Cluster: Feature"),
    CWE_996(996, "SFP Secondary Cluster: Security"),
    CWE_997(997, "SFP Secondary Cluster: Information Loss"),
    CWE_998(998, "SFP Secondary Cluster: Glitch in Computation"),
    CWE_1001(1001, "SFP Secondary Cluster: Use of an Improper API"),
    CWE_1002(1002, "SFP Secondary Cluster: Unexpected Entry Points");

    private int id;
    private String desc;

    CWE(int id, String desc) {
        this.id = id;
        this.desc = desc;
    }

    public int getId() {
        return id;
    }

    public String getDesc() {
        return desc;
    }

}
