package us.springett.threatmodeling.model;

/**
 * The current state of the Threat mapped to the Microsoft TAM tool.
 */
public enum ThreatState {
    AUTO_GENERATED("AutoGenerated"),
    MITIGATED("Mitigated"),
    NOT_APPLICABLE("NotApplicable"),
    NEEDS_INVESTIGATION("NeedsInvestigation");

    private String name;

    ThreatState(String name) {
        this.name = name;
    }

    public static ThreatState fromString(String text) {
        for (ThreatState state : ThreatState.values()) {
            if (state.name.equalsIgnoreCase(text)) {
                return state;
            }
        }
        return null;
    }

}
